import { DashboardCatalog } from "../../dashboard";
import {
  TicketActivityChart,
  TicketFrontlineChart,
  TicketStatusChart,
  TicketTypeChart,
} from "../charts";
import { TicketReporterBoard } from "../reports";
import { TicketLeaderboard } from "../tickets";

export const modDashboardCatalog: DashboardCatalog = {
  tickets: {
    defaultLayout: {
      xl: { x: 0, y: 0, w: 6, h: 11, minW: 3, maxW: 6, minH: 9, maxH: 20 },
      lg: { x: 0, y: 0, w: 4, h: 11, minW: 3, maxW: 6, minH: 9, maxH: 20 },
      md: { x: 0, y: 0, w: 6, h: 11, minW: 3, maxW: 6, minH: 9, maxH: 20 },
      sm: { x: 0, y: 0, w: 6, h: 11, minW: 3, maxW: 6, minH: 9, maxH: 20 },
      xs: { x: 0, y: 0, w: 4, h: 11, minW: 3, maxW: 6, minH: 9, maxH: 20 },
    },
    card: {
      title: "Tickets",
      variant: "outlined",
    },
    component: TicketLeaderboard,
  },
  volume: {
    defaultLayout: {
      xl: { x: 6, y: 0, w: 5, h: 5, minW: 3, maxW: 5, minH: 4, maxH: 9 },
      lg: { x: 4, y: 0, w: 4, h: 5, minW: 3, maxW: 5, minH: 4, maxH: 9 },
      md: { x: 6, y: 0, w: 3, h: 5, minW: 3, maxW: 5, minH: 4, maxH: 9 },
      sm: { x: 0, y: 11, w: 3, h: 5, minW: 3, maxW: 5, minH: 4, maxH: 9 },
      xs: { x: 0, y: 11, w: 4, h: 5, minW: 3, maxW: 5, minH: 4, maxH: 9 },
    },
    card: { title: "Volume" },
    component: TicketStatusChart,
  },
  type: {
    defaultLayout: {
      xl: { x: 11, y: 0, w: 5, h: 6, minW: 3, maxW: 5, minH: 4, maxH: 9 },
      lg: { x: 4, y: 5, w: 4, h: 6, minW: 3, maxW: 5, minH: 4, maxH: 9 },
      md: { x: 6, y: 5, w: 3, h: 6, minW: 3, maxW: 5, minH: 4, maxH: 9 },
      sm: { x: 3, y: 11, w: 3, h: 6, minW: 3, maxW: 5, minH: 4, maxH: 9 },
      xs: { x: 0, y: 16, w: 4, h: 6, minW: 3, maxW: 5, minH: 4, maxH: 9 },
    },
    card: { title: "Type" },
    component: TicketTypeChart,
  },
  activity: {
    defaultLayout: {
      xl: {
        x: 0,
        y: 11,
        w: 8,
        h: 5,
        minW: 4,
        maxW: undefined,
        minH: 3,
        maxH: 9,
      },
      lg: {
        x: 0,
        y: 11,
        w: 6,
        h: 5,
        minW: 4,
        maxW: undefined,
        minH: 3,
        maxH: 9,
      },
      md: {
        x: 0,
        y: 11,
        w: 6,
        h: 5,
        minW: 4,
        maxW: undefined,
        minH: 3,
        maxH: 9,
      },
      sm: {
        x: 0,
        y: 16,
        w: 6,
        h: 5,
        minW: 4,
        maxW: undefined,
        minH: 3,
        maxH: 9,
      },
      xs: {
        x: 0,
        y: 22,
        w: 4,
        h: 5,
        minW: 4,
        maxW: undefined,
        minH: 3,
        maxH: 9,
      },
    },
    card: { title: "Activity" },
    component: TicketActivityChart,
  },
  reporters: {
    defaultLayout: {
      xl: { x: 8, y: 11, w: 4, h: 11, minW: 2, maxW: 4, minH: 7, maxH: 15 },
      lg: { x: 8, y: 0, w: 4, h: 11, minW: 2, maxW: 4, minH: 7, maxH: 15 },
      md: { x: 9, y: 0, w: 3, h: 11, minW: 2, maxW: 4, minH: 7, maxH: 15 },
      sm: { x: 0, y: 21, w: 6, h: 11, minW: 2, maxW: 4, minH: 7, maxH: 15 },
      xs: { x: 0, y: 27, w: 4, h: 11, minW: 2, maxW: 4, minH: 7, maxH: 15 },
    },
    card: { title: "Reporters", variant: "outlined" },
    component: TicketReporterBoard,
  },
  frontline: {
    defaultLayout: {
      xl: {
        x: 12,
        y: 11,
        w: 4,
        h: 5,
        minW: 4,
        maxW: undefined,
        minH: 3,
        maxH: 9,
      },
      lg: {
        x: 8,
        y: 11,
        w: 6,
        h: 5,
        minW: 4,
        maxW: undefined,
        minH: 3,
        maxH: 9,
      },
      md: {
        x: 9,
        y: 11,
        w: 3,
        h: 5,
        minW: 4,
        maxW: undefined,
        minH: 3,
        maxH: 9,
      },
      sm: {
        x: 0,
        y: 32,
        w: 6,
        h: 5,
        minW: 4,
        maxW: undefined,
        minH: 3,
        maxH: 9,
      },
      xs: {
        x: 0,
        y: 38,
        w: 4,
        h: 5,
        minW: 4,
        maxW: undefined,
        minH: 3,
        maxH: 9,
      },
    },
    card: { title: "Frontline" },
    component: TicketFrontlineChart,
  },
};
