services:
  six-oclock:
    profiles:
      - app

  six-oclock-postgres:
    ports:
      - "127.0.0.1:34572:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 3s
      retries: 15

  six-oclock-redis:
    ports:
      - "127.0.0.1:34573:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 3s
      retries: 15
