/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * @6oclock/api
 * backend data aggregate for 6 o'clock
 * OpenAPI spec version: 1.0.0
 */

export type Activity = (typeof Activity)[keyof typeof Activity];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Activity = {
  post_create: 'post_create',
  post_delete: 'post_delete',
  post_approve: 'post_approve',
  post_replacement_create: 'post_replacement_create',
  post_replacement_approve: 'post_replacement_approve',
  post_replacement_promote: 'post_replacement_promote',
  post_replacement_reject: 'post_replacement_reject',
  flag_handle: 'flag_handle',
  ticket_create: 'ticket_create',
  ticket_handle: 'ticket_handle',
} as const;
