/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * 5-thirty
 * backend data aggregate for 6 o'clock
 * OpenAPI spec version: 0.0.8
 */

export interface ActivitySeriesPoint {
  postCreate: number;
  postDelete: number;
  postApprove: number;
  postReplacementCreate: number;
  postReplacementApprove: number;
  postReplacementReject: number;
  postReplacementPromote: number;
  ticketCreate: number;
  ticketHandle: number;
  date: Date;
}
