/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * @6oclock/api
 * backend data aggregate for 6 o'clock
 * OpenAPI spec version: 1.0.0
 */
import type { DashboardPosition } from './dashboardPosition';

export interface DashboardPositions {
  xs?: DashboardPosition[];
  sm?: DashboardPosition[];
  md?: DashboardPosition[];
  lg?: DashboardPosition[];
  xl?: DashboardPosition[];
}
