/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * @6oclock/api
 * backend data aggregate for 6 o'clock
 * OpenAPI spec version: 1.0.0
 */
import type { DashboardConfigMeta } from './dashboardConfigMeta';
import type { DashboardConfigType } from './dashboardConfigType';
import type { DashboardPositions } from './dashboardPositions';

export interface DashboardConfig {
  type: DashboardConfigType;
  userId: number;
  version: number;
  positions: DashboardPositions;
  meta: DashboardConfigMeta;
}
