/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * 5-thirty
 * backend data aggregate for 6 o'clock
 * OpenAPI spec version: 0.0.8
 */
import type { DashboardPosition } from './dashboardPosition';

export interface DashboardPositions {
  xs?: DashboardPosition[];
  sm?: DashboardPosition[];
  md?: DashboardPosition[];
  lg?: DashboardPosition[];
  xl?: DashboardPosition[];
}
