/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * @6oclock/api
 * backend data aggregate for 6 o'clock
 * OpenAPI spec version: 1.0.0
 */

export type DashboardConfigType = typeof DashboardConfigType[keyof typeof DashboardConfigType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DashboardConfigType = {
  moderator: 'moderator',
  janitor: 'janitor',
  admin: 'admin',
} as const;
