/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * 5-thirty
 * backend data aggregate for 6 o'clock
 * OpenAPI spec version: 0.0.3
 */
import type { DashboardPosition } from './dashboardPosition';

export interface DashboardPositions {
  lg?: DashboardPosition[];
  md?: DashboardPosition[];
  sm?: DashboardPosition[];
  xl?: DashboardPosition[];
  xs?: DashboardPosition[];
}
