/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * 5-thirty
 * backend data aggregate for 6 o'clock
 * OpenAPI spec version: 0.0.4
 */
import type { GetApprovalCountSummaryScale } from './getApprovalCountSummaryScale';

export type GetApprovalCountSummaryParams = {
  startDate?: Date;
  endDate?: Date;
  timezone?: string;
  scale?: GetApprovalCountSummaryScale;
};
