/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * 5-thirty
 * backend data aggregate for 6 o'clock
 * OpenAPI spec version: 0.0.5
 */

export type GetActivityArea =
  (typeof GetActivityArea)[keyof typeof GetActivityArea];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetActivityArea = {
  admin: 'admin',
  moderator: 'moderator',
  janitor: 'janitor',
  member: 'member',
} as const;
