/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * 5-thirty
 * backend data aggregate for 6 o'clock
 * OpenAPI spec version: 0.0.5
 */
import type { GetApproverSummaryScale } from './getApproverSummaryScale';

export type GetApproverSummaryParams = {
  startDate?: Date;
  endDate?: Date;
  timezone?: string;
  scale?: GetApproverSummaryScale;
  /**
   * Page number
   */
  page?: number;
  /**
   * Page size
   */
  limit?: number;
};
