/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * 5-thirty
 * backend data aggregate for 6 o'clock
 * OpenAPI spec version: 0.0.3
 */

export type GetDeletionActivitySummaryByDeleterScale =
  (typeof GetDeletionActivitySummaryByDeleterScale)[keyof typeof GetDeletionActivitySummaryByDeleterScale];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetDeletionActivitySummaryByDeleterScale = {
  minute: 'minute',
  hour: 'hour',
  day: 'day',
  week: 'week',
  month: 'month',
  year: 'year',
  decade: 'decade',
  all: 'all',
} as const;
