/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.
 * OpenAPI spec version: 1.0.0
 */

export type GetPostApprovalsParams = {
  /**
   * The page number to retrieve
   */
  page?: number;
  /**
   * The number of approvals to retrieve per page
   */
  limit?: number;
  /**
   * Filter approvals by approver username
   */
  "search[user_name]"?: number;
  /**
   * Filter approvals by matching post tagss
   */
  "search[post_tags_match]"?: number;
  /**
   * Filter by the creation date of the approval
   */
  "search[created_at]"?: string;
  /**
   * Filter by the last update date of the approval
   */
  "search[updated_at]"?: string;
};
