/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * @6oclock/api
 * backend data aggregate for 6 o'clock
 * OpenAPI spec version: 1.0.0
 */
import type { TimeScale } from './timeScale';

export type GetPostStatusSummaryParams = {
scale?: TimeScale;
cycle?: TimeScale;
startDate?: Date;
endDate?: Date;
timezone?: string;
};
