/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.
 * OpenAPI spec version: 1.0.0
 */

export type GetPostsJsonParams = {
  /**
   * The page number for pagination
   */
  page?: number;
  /**
   * The number of posts to retrieve per page
   */
  limit?: number;
  /**
   * Filter posts by tags
   */
  tags?: string;
};
