/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.
 * OpenAPI spec version: 1.0.0
 */
import type { GetUserFeedbacksJsonSearchCategory } from "./getUserFeedbacksJsonSearchCategory";
import type { GetUserFeedbacksJsonSearchDeleted } from "./getUserFeedbacksJsonSearchDeleted";

export type GetUserFeedbacksJsonParams = {
  /**
   * The page number to retrieve
   */
  page?: number;
  /**
   * The number of feedbacks to retrieve per page
   */
  limit?: number;
  /**
   * Filter by feedback category
   */
  "search[category]"?: GetUserFeedbacksJsonSearchCategory;
  /**
   * Filter by deletion status of the feedback
   */
  "search[deleted]"?: GetUserFeedbacksJsonSearchDeleted;
};
