/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.
 * OpenAPI spec version: 1.0.0
 */

export type GetUserFeedbacksSearchCategory =
  (typeof GetUserFeedbacksSearchCategory)[keyof typeof GetUserFeedbacksSearchCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetUserFeedbacksSearchCategory = {
  negative: "negative",
  positive: "positive",
  neutral: "neutral",
} as const;
