/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.
 * OpenAPI spec version: 1.0.0
 */

export type GetUploadsSearchStatus =
  (typeof GetUploadsSearchStatus)[keyof typeof GetUploadsSearchStatus];

 
export const GetUploadsSearchStatus = {
  completed: "completed",
  processing: "processing",
  pending: "pending",
  duplicate: "duplicate",
  error: "error",
} as const;
