/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.
 * OpenAPI spec version: 1.0.0
 */

export type GetUserFeedbacksJsonSearchDeleted =
  (typeof GetUserFeedbacksJsonSearchDeleted)[keyof typeof GetUserFeedbacksJsonSearchDeleted];

 
export const GetUserFeedbacksJsonSearchDeleted = {
  included: "included",
  excluded: "excluded",
  only: "only",
} as const;
