/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.
 * OpenAPI spec version: 1.0.0
 */

export type GetUserFeedbacksJsonSearchCategory =
  (typeof GetUserFeedbacksJsonSearchCategory)[keyof typeof GetUserFeedbacksJsonSearchCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetUserFeedbacksJsonSearchCategory = {
  negative: "negative",
  positive: "positive",
  neutral: "neutral",
} as const;
