/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * 5-thirty
 * backend data aggregate for 6 o'clock
 * OpenAPI spec version: 0.0.6
 */

export type ItemType = (typeof ItemType)[keyof typeof ItemType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ItemType = {
  approvals: 'approvals',
  tickets: 'tickets',
  posts: 'posts',
  users: 'users',
  user_profiles: 'user_profiles',
  flags: 'flags',
  feedbacks: 'feedbacks',
  post_versions: 'post_versions',
  post_replacements: 'post_replacements',
  mod_actions: 'mod_actions',
} as const;
