/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * 5-thirty
 * backend data aggregate for 6 o'clock
 * OpenAPI spec version: 1.0.0
 */

export interface JobInfo {
  id: number;
  title: string;
  key?: string;
  startedAt?: Date;
  endedAt?: Date;
  succeeded: boolean;
  failed: boolean;
  cancelled: boolean;
  timedOut: boolean;
}
