/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * @6oclock/api
 * backend data aggregate for 6 o'clock
 * OpenAPI spec version: 1.0.0
 */

export type JobOverviewOutcome =
  (typeof JobOverviewOutcome)[keyof typeof JobOverviewOutcome];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const JobOverviewOutcome = {
  active: 'active',
  waiting: 'waiting',
  delayed: 'delayed',
  completed: 'completed',
  failed: 'failed',
  timedOut: 'timedOut',
} as const;
