/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * 5-thirty
 * backend data aggregate for 6 o'clock
 * OpenAPI spec version: 0.0.8
 */
import type { ItemType } from './itemType';

export interface Manifest {
  endDate: Date;
  id: number;
  lowerId: number;
  startDate: Date;
  type: ItemType;
  upperId: number;
}
