/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * 5-thirty
 * backend data aggregate for 6 o'clock
 * OpenAPI spec version: 0.0.8
 */
import type { ManifestSlice } from './manifestSlice';
import type { ItemType } from './itemType';

export interface ManifestHealth {
  count: number;
  endDate: Date;
  endId: number;
  id: number;
  slices: ManifestSlice[];
  startDate: Date;
  startId: number;
  type: ItemType;
}
