/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * 5-thirty
 * backend data aggregate for 6 o'clock
 * OpenAPI spec version: 1.0.0
 */
import type { ItemType } from './itemType';
import type { ManifestSlice } from './manifestSlice';

export interface ManifestHealth {
  type: ItemType;
  id: number;
  porous: boolean;
  startDate: Date;
  endDate: Date;
  startId: number;
  endId: number;
  count: number;
  slices: ManifestSlice[];
}
