/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * @6oclock/api
 * backend data aggregate for 6 o'clock
 * OpenAPI spec version: 1.0.0
 */
import type { PerformanceWeightsWeights } from './performanceWeightsWeights';
import type { UserArea } from './userArea';

export interface PerformanceWeights {
  area: UserArea;
  weights: PerformanceWeightsWeights;
}
