/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * 5-thirty
 * backend data aggregate for 6 o'clock
 * OpenAPI spec version: 1.0.0
 */

export type PerformanceGrade = typeof PerformanceGrade[keyof typeof PerformanceGrade];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PerformanceGrade = {
  F: 'F',
  E: 'E',
  D: 'D',
  C: 'C',
  B: 'B',
  A: 'A',
  S: 'S',
  S2: 'S2',
  S3: 'S3',
  S4: 'S4',
  S5: 'S5',
  S6: 'S6',
} as const;
