/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * 5-thirty
 * backend data aggregate for 6 o'clock
 * OpenAPI spec version: 0.0.7
 */
import type { ActivitySummary } from './activitySummary';
import type { UserHead } from './userHead';
import type { PerformanceRecord } from './performanceRecord';
import type { PerformanceGrade } from './performanceGrade';
import type { TrendGrade } from './trendGrade';

export interface PerformanceSummary {
  activity: ActivitySummary;
  days: number;
  head?: UserHead;
  history: PerformanceRecord[];
  position: number;
  score: number;
  scoreGrade: PerformanceGrade;
  trend: number;
  trendGrade: TrendGrade;
  userId: number;
}
