/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * 5-thirty
 * backend data aggregate for 6 o'clock
 * OpenAPI spec version: 0.0.8
 */

export interface PostReplacementHandledPoint {
  approved: number;
  date: Date;
  promoted: number;
  rejected: number;
}
