/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.
 * OpenAPI spec version: 1.0.0
 */
import type { PostFlagType } from "./postFlagType";

/**
 * A post flag object representing a user's flag or deletion request on a post.
 */
export interface PostFlag {
  /** The timestamp when the post flag was created */
  created_at: Date;
  /** The ID of the user who created the flag or deletion request */
  creator_id: number;
  /** The unique ID of the post flag */
  id: number;
  /** Whether the flag is a deletion request */
  is_deletion: boolean;
  /** Whether the flag has been resolved */
  is_resolved: boolean;
  /** The ID of the post that the flag is related to */
  post_id: number;
  /** The reason for the flag or deletion request */
  reason: string;
  /** The type of the flag (e.g., flag or deletion) */
  type: PostFlagType;
  /** The timestamp when the post flag was last updated */
  updated_at: Date;
}
