/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.
 * OpenAPI spec version: 1.0.0
 */

/**
 * The rating of the post (e.g., safe, questionable, explicit)
 */
export type PostVersionRating =
  (typeof PostVersionRating)[keyof typeof PostVersionRating];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostVersionRating = {
  s: "s",
  q: "q",
  e: "e",
} as const;
