/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.
 * OpenAPI spec version: 1.0.0
 */

/**
 * The type of the flag (e.g., flag or deletion)
 */
export type PostFlagType = (typeof PostFlagType)[keyof typeof PostFlagType];

 
export const PostFlagType = {
  flag: "flag",
  deletion: "deletion",
} as const;
