/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * 5-thirty
 * backend data aggregate for 6 o'clock
 * OpenAPI spec version: 0.0.8
 */
import type { UserHead } from './userHead';

export interface PostUploaderSummary {
  userId: number;
  head?: UserHead;
  total: number;
  position: number;
  days: number;
}
