/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * 5-thirty
 * backend data aggregate for 6 o'clock
 * OpenAPI spec version: 0.0.1
 */
import type { TicketAgeGroup } from './ticketAgeGroup';

export interface TicketAgeSeriesPoint {
  date: Date;
  groups: TicketAgeGroup;
}
