/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * 5-thirty
 * backend data aggregate for 6 o'clock
 * OpenAPI spec version: 0.0.4
 */

export interface TicketStatusSummary {
  approved: number;
  partial: number;
  pending: number;
}
