/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * @6oclock/api
 * backend data aggregate for 6 o'clock
 * OpenAPI spec version: 1.0.0
 */

export interface TicketAgeSummary {
  oneDay: number;
  threeDays: number;
  oneWeek: number;
  twoWeeks: number;
  oneMonth: number;
  aboveOneMonth: number;
}
