/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * 5-thirty
 * backend data aggregate for 6 o'clock
 * OpenAPI spec version: 0.0.4
 */
import type { UserHead } from './userHead';

export interface TicketReporterSummary {
  days: number;
  head?: UserHead;
  total: number;
  userId: number;
}
