/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * @6oclock/api
 * backend data aggregate for 6 o'clock
 * OpenAPI spec version: 1.0.0
 */

export type TimeScale = (typeof TimeScale)[keyof typeof TimeScale];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TimeScale = {
  minute: 'minute',
  hour: 'hour',
  day: 'day',
  week: 'week',
  month: 'month',
  year: 'year',
  decade: 'decade',
  all: 'all',
} as const;
