/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * 5-thirty
 * backend data aggregate for 6 o'clock
 * OpenAPI spec version: 0.0.8
 */

export interface UserCredentials {
  /** @minLength 1 */
  username: string;
  /** @pattern /^[a-zA-Z0-9]{24,32}$/ */
  password: string;
}
