/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * @6oclock/api
 * backend data aggregate for 6 o'clock
 * OpenAPI spec version: 1.0.0
 */

export type UserArea = typeof UserArea[keyof typeof UserArea];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserArea = {
  admin: 'admin',
  moderator: 'moderator',
  janitor: 'janitor',
  member: 'member',
} as const;
