/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

export interface AddPoolElementBody {
  /** The ID of the pool */
  pool_id?: number;
  /** The name of the pool (alternative to pool_id) */
  pool_name?: string;
  /** The ID of the post to add */
  post_id: number;
}
