/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.

## Authentication

Endpoints with `x-access-level` above `anonymous` require authentication.
Credentials are the account username and an API key issued by `/api_keys.json`,
submitted as either HTTP Basic (username, API key) or the query/body parameters
`login` and `api_key`.

The `x-access-level` extension declares the minimum privilege level for an
operation: `anonymous`, `logged_in`, `member`, `janitor`, `moderator`, `admin`.

 * OpenAPI spec version: dadc1e4c50658851c0205e6ecbfa4723a976b0ab
 */

/**
 * An API key for authenticating API requests.
 */
export interface ApiKey {
  /** When the API key was created */
  created_at: Date;
  /**
   * When the API key expires
   * @nullable
   */
  expires_at?: Date | null;
  /** The unique ID of the API key */
  id: number;
  /** The API key token (only shown on creation) */
  key?: string;
  /**
   * The last IP address that used this key
   * @nullable
   */
  last_ip_address?: string | null;
  /**
   * When the API key was last used
   * @nullable
   */
  last_used_at?: Date | null;
  /** The name of the API key */
  name: string;
  /** When the API key was last updated */
  updated_at: Date;
  /** The ID of the user who owns the key */
  user_id: number;
}
