/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */
import type { AppealQtype } from './appealQtype';
import type { AppealStatus } from './appealStatus';

/**
 * An appeal raised against a moderation action (currently only flag appeals).
Field visibility depends on viewer permissions: users without view access
do not receive `creator_id`, `accused_id`, `reason`, or `response`; non-staff
users do not receive `claimant_id`.

 */
export interface Appeal {
  /** The unique ID of the appeal */
  id: number;
  /** The ID of the user who created the appeal */
  creator_id: number;
  /** The ID of the appealed record (e.g. a PostFlag ID when `qtype=flag`) */
  disp_id: number;
  qtype: AppealQtype;
  status: AppealStatus;
  /** The reason given for the appeal */
  reason: string;
  /** The handler's response to the appeal */
  response: string;
  /**
   * The ID of the staff member currently claiming the appeal
   * @nullable
   */
  claimant_id?: number | null;
  /**
   * The ID of the staff member who last updated the appeal
   * @nullable
   */
  handler_id?: number | null;
  /**
   * The ID of the user the appeal is filed against (e.g. the flag creator for flag appeals)
   * @nullable
   */
  accused_id?: number | null;
  /** The time the appeal was created */
  created_at: Date;
  /** The last time the appeal was updated */
  updated_at: Date;
}
