/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

/**
 * The current status of the appeal
 */
export enum AppealStatus {
  pending = 'pending',
  partial = 'partial',
  approved = 'approved',
  rejected = 'rejected',
}
