/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.

## Authentication

Endpoints with `x-access-level` above `anonymous` require authentication.
Credentials are the account username and an API key issued by `/api_keys.json`,
submitted as either HTTP Basic (username, API key) or the query/body parameters
`login` and `api_key`.

The `x-access-level` extension declares the minimum privilege level for an
operation: `anonymous`, `logged_in`, `member`, `janitor`, `moderator`, `admin`.

 * OpenAPI spec version: dadc1e4c50658851c0205e6ecbfa4723a976b0ab
 */

/**
 * A version history entry for an artist.
 */
export interface ArtistVersion {
  /** The unique ID of the version */
  id: number;
  /** The ID of the artist */
  artist_id: number;
  /** The artist's name at this version */
  name: string;
  /** The ID of the user who made this version */
  updater_id: number;
  /** Whether the artist was active at this version */
  is_active: boolean;
  /** The artist's group name at this version */
  group_name?: string;
  /** The artist's other names at this version */
  other_names?: string[];
  /** The artist's URLs at this version */
  urls?: string[];
  /**
   * Whether the artist's notes were changed in this version
   * @nullable
   */
  notes_changed?: boolean | null;
  /** When this version was created */
  created_at: Date;
  /** When this version was last updated */
  updated_at: Date;
}
