/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

export interface ArtistUrl {
  /** The unique ID of the URL entry */
  id?: number;
  /** The ID of the associated artist */
  artist_id?: number;
  /** The URL */
  url?: string;
  /** The normalized form of the URL */
  normalized_url?: string;
  /** Whether the URL is active */
  is_active?: boolean;
  /** The time when the URL was added */
  created_at?: Date;
  /** The last time the URL was updated */
  updated_at?: Date;
}
