/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.

## Authentication

Endpoints with `x-access-level` above `anonymous` require authentication.
Credentials are the account username and an API key issued by `/api_keys.json`,
submitted as either HTTP Basic (username, API key) or the query/body parameters
`login` and `api_key`.

The `x-access-level` extension declares the minimum privilege level for an
operation: `anonymous`, `logged_in`, `member`, `janitor`, `moderator`, `admin`.

 * OpenAPI spec version: dadc1e4c50658851c0205e6ecbfa4723a976b0ab
 */
import type { ArtistUrl } from './artistUrl';

export interface Artist {
  /** The unique ID of the artist */
  id: number;
  /** The artist's tag name */
  name: string;
  /** The ID of the user who created the artist entry */
  creator_id: number;
  /** Whether the artist is active */
  is_active: boolean;
  /** Whether the artist page is locked for editing */
  is_locked: boolean;
  /** Alternative names for the artist */
  other_names: string[];
  /** The name of the artist group or circle */
  group_name: string;
  /**
   * The ID of the linked user account
   * @nullable
   */
  linked_user_id: number | null;
  /** The time when the artist was created */
  created_at: Date;
  /** The last time the artist was updated */
  updated_at: Date;
  /** The artist's URLs */
  urls?: ArtistUrl[];
}
