/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

/**
 * A version history entry for an artist.
 */
export interface ArtistVersion {
  /** The unique ID of the version */
  id: number;
  /** The ID of the artist */
  artist_id: number;
  /** The artist's name at this version */
  name: string;
  /** The ID of the user who made this version */
  updater_id: number;
  /** Whether the artist was active at this version */
  is_active: boolean;
  /** The artist's group name at this version */
  group_name?: string;
  /** The artist's other names at this version */
  other_names?: string[];
  /** The artist's URLs at this version */
  urls?: string[];
  /**
   * Whether the artist's notes were changed in this version
   * @nullable
   */
  notes_changed?: boolean | null;
  /** When this version was created */
  created_at: Date;
  /** When this version was last updated */
  updated_at: Date;
}
