/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

/**
 * A version history entry for an avoid posting record.
 */
export interface AvoidPostingVersion {
  /** The unique ID of the version */
  id: number;
  /** The ID of the user who made this version */
  updater_id: number;
  /** The ID of the associated avoid posting entry */
  avoid_posting_id: number;
  /** Details at this version */
  details?: string;
  /** Staff notes at this version (hidden from non-janitors) */
  staff_notes?: string;
  /** Whether the entry was active at this version */
  is_active: boolean;
  /** When this version was created */
  updated_at: Date;
}
