/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */
import type { BasicPostAllOf } from './basicPostAllOf';
import type { PostBase } from './postBase';

/**
 * Basic v2 Post payload (`v2=true`, `mode` unset or `basic`). Tags are a flat array of strings.
 */
export type BasicPost = PostBase & BasicPostAllOf;
