/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

/**
 * The vote score (1 for upvote, -1 for downvote, 0 for locked)
 */
export enum CommentVoteScore {
  NUMBER_MINUS_1 = -1,
  NUMBER_0 = 0,
  NUMBER_1 = 1,
}
