/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.

## Authentication

Endpoints with `x-access-level` above `anonymous` require authentication.
Credentials are the account username and an API key issued by `/api_keys.json`,
submitted as either HTTP Basic (username, API key) or the query/body parameters
`login` and `api_key`.

The `x-access-level` extension declares the minimum privilege level for an
operation: `anonymous`, `logged_in`, `member`, `janitor`, `moderator`, `admin`.

 * OpenAPI spec version: dadc1e4c50658851c0205e6ecbfa4723a976b0ab
 */
import type { CommentVoteScore } from './commentVoteScore';

export interface CommentVote {
  /** The unique ID of the comment vote */
  id: number;
  /** The ID of the comment that was voted on */
  comment_id: number;
  /** The ID of the user who voted */
  user_id: number;
  score: CommentVoteScore;
  /** The time when the vote was cast */
  created_at: Date;
  /** The last time the vote was updated */
  updated_at: Date;
}
