/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */
import type { CommentVoteScore } from './commentVoteScore';

export interface CommentVote {
  /** The unique ID of the comment vote */
  id: number;
  /** The ID of the comment that was voted on */
  comment_id: number;
  /** The ID of the user who voted */
  user_id: number;
  score: CommentVoteScore;
  /** The time when the vote was cast */
  created_at: Date;
  /** The last time the vote was updated */
  updated_at: Date;
}
