/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */
import type { CreateOauthTokenBodyGrantType } from './createOauthTokenBodyGrantType';

export interface CreateOauthTokenBody {
  /** The grant type. `authorization_code` is the only enabled flow, and `refresh_token` may be used to renew a token. */
  grant_type: CreateOauthTokenBodyGrantType;
  /** The application's client identifier */
  client_id: string;
  /** The application's client secret, for confidential clients */
  client_secret?: string;
  /** The authorization code, for `grant_type=authorization_code` */
  code?: string;
  /** The redirect URI used in the authorization request */
  redirect_uri?: string;
  /** The PKCE code verifier. Required, since PKCE is enforced. */
  code_verifier?: string;
  /** The refresh token, for `grant_type=refresh_token` */
  refresh_token?: string;
}
