/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */
import type { CreatePostVoteBodyScore } from './createPostVoteBodyScore';

export interface CreateCommentVoteBody {
  score: CreatePostVoteBodyScore;
  /** If true, do not unvote when voting again with the same score */
  no_unvote?: boolean;
}
