/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */
import type { TakedownStatus } from './takedownStatus';

export interface CreateTakedownBodyTakedown {
  /** The contact email address for the request */
  email: string;
  /** The source the content was taken from */
  source?: string;
  /** Instructions for handling the request */
  instructions?: string;
  /** The reason for the takedown */
  reason: string;
  /** Post IDs or post URLs to take down; digit runs are extracted from the value */
  post_ids?: string;
  /** Whether the reason is hidden from non-staff */
  reason_hidden?: boolean;
  /** Staff notes for the takedown (BD staff only) */
  notes?: string;
  /** Post IDs to mark for deletion (BD staff only) */
  del_post_ids?: string;
  /** The takedown status (BD staff only). A create always overwrites this with "pending". */
  status?: TakedownStatus;
}
