/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

export interface CreateCommentBodyComment {
  /** The comment body text */
  body: string;
  /** The ID of the post to comment on */
  post_id: number;
  /** Whether to bump the post */
  do_not_bump_post?: boolean;
  /** Whether the comment is sticky (janitor only) */
  is_sticky?: boolean;
  /** Whether the comment is hidden (moderator only) */
  is_hidden?: boolean;
}
