/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

export interface CreateIpBanBody {
  /** The IP address or CIDR range to ban */
  'ip_ban[ip_addr]': string;
  /** The reason for the ban */
  'ip_ban[reason]': string;
}
