/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */
import type { CreateStaffWikiBodyStaffWiki } from './createStaffWikiBodyStaffWiki';

export interface CreateStaffWikiBody {
  staff_wiki: CreateStaffWikiBodyStaffWiki;
}
