/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

export interface CreateDtextPreviewBody {
  /** The DText markup to render */
  body?: string;
  /** Whether to allow color tags */
  allow_color?: boolean;
}
