/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */
import type { CreateTagCorrectionBodyCommit } from './createTagCorrectionBodyCommit';

export interface CreateTagCorrectionBody {
  /** Must be Fix for the correction to be queued */
  commit?: CreateTagCorrectionBodyCommit;
  /** Redirect to the tag's wiki page instead of the tag search */
  from_wiki?: boolean;
}
