/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

export interface CreateNoteBodyNote {
  /** The ID of the post to attach the note to */
  post_id: number;
  /** X coordinate of the note */
  x: number;
  /** Y coordinate of the note */
  y: number;
  /** Width of the note */
  width: number;
  /** Height of the note */
  height: number;
  /** The body text of the note */
  body: string;
  /** HTML element ID for the note */
  html_id?: string;
}
