/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */
import type { PostDisapprovalReason } from './postDisapprovalReason';

export interface CreatePostDisapprovalBodyPostDisapproval {
  /** The ID of the post to disapprove */
  post_id: number;
  reason: PostDisapprovalReason;
  /** Optional message explaining the disapproval */
  message?: string;
}
