/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.

## Authentication

Endpoints with `x-access-level` above `anonymous` require authentication.
Credentials are the account username and an API key issued by `/api_keys.json`,
submitted as either HTTP Basic (username, API key) or the query/body parameters
`login` and `api_key`.

The `x-access-level` extension declares the minimum privilege level for an
operation: `anonymous`, `logged_in`, `member`, `janitor`, `moderator`, `admin`.

 * OpenAPI spec version: dadc1e4c50658851c0205e6ecbfa4723a976b0ab
 */

export interface CreateWikiPageBodyWikiPage {
  /** The title of the wiki page */
  title: string;
  /** The body content of the wiki page */
  body: string;
  /** The tag category ID */
  category_id?: number;
  /** The reason for the edit */
  edit_reason?: string;
  /** The parent wiki page title (privileged+ only) */
  parent?: string;
  /** Whether the page is locked (janitor+ only) */
  is_locked?: boolean;
  /** Whether the page is deleted (janitor+ only) */
  is_deleted?: boolean;
}
