/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.

## Authentication

Endpoints with `x-access-level` above `anonymous` require authentication.
Credentials are the account username and an API key issued by `/api_keys.json`,
submitted as either HTTP Basic (username, API key) or the query/body parameters
`login` and `api_key`.

The `x-access-level` extension declares the minimum privilege level for an
operation: `anonymous`, `logged_in`, `member`, `janitor`, `moderator`, `admin`.

 * OpenAPI spec version: dadc1e4c50658851c0205e6ecbfa4723a976b0ab
 */

export interface CreateCommentBodyComment {
  /** The comment body text */
  body: string;
  /** The ID of the post to comment on */
  post_id: number;
  /** Whether to bump the post */
  do_not_bump_post?: boolean;
  /** Whether the comment is sticky (janitor only) */
  is_sticky?: boolean;
  /** Whether the comment is hidden (moderator only) */
  is_hidden?: boolean;
}
