/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

export interface CreateUploadWhitelistBody {
  /** Whether uploads from this domain are allowed */
  'upload_whitelist[allowed]'?: boolean;
  /** The domain pattern */
  'upload_whitelist[domain]'?: string;
  /** The path pattern */
  'upload_whitelist[path]'?: string;
  /** The reason for the whitelist entry */
  'upload_whitelist[reason]'?: string;
  /** Note about the whitelist entry */
  'upload_whitelist[note]'?: string;
  /** Whether the entry is hidden */
  'upload_whitelist[hidden]'?: boolean;
}
