/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

export interface CreatePostSetBodyPostSet {
  name: string;
  shortname: string;
  description?: string;
  is_public?: boolean;
  transfer_on_delete?: boolean;
}
