/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

export interface CreateUserBodyUser {
  /** The desired username */
  name: string;
  /** The user's email address */
  email: string;
  /** The password for the account */
  password: string;
  /** Password confirmation */
  password_confirmation: string;
}
