/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */
import type { StaffWikiRefType } from './staffWikiRefType';

export interface CreateStaffWikiBodyStaffWiki {
  /**
   * The title of the page, which must be unique
   * @minLength 1
   * @maxLength 100
   */
  title: string;
  /** The DText body of the page */
  body?: string;
  related_type?: StaffWikiRefType;
  /** The ID of the record to reference, of the type given by `related_type` */
  related_id?: number;
}
