/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

/**
 * A direct message between users.
 */
export interface Dmail {
  /** The unique ID of the DMail */
  id: number;
  /** The ID of the user who owns this copy of the DMail */
  owner_id: number;
  /** The ID of the sender */
  from_id: number;
  /** The ID of the recipient */
  to_id: number;
  /** The subject line of the DMail */
  title: string;
  /** The body text of the DMail */
  body: string;
  /** Whether the DMail has been read */
  is_read: boolean;
  /** Whether the DMail has been deleted */
  is_deleted: boolean;
  /** The recipient's username */
  to_name?: string;
  /** The sender's username */
  from_name?: string;
  /** When the DMail was created */
  created_at: Date;
  /** When the DMail was last updated */
  updated_at: Date;
}
