/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.

## Authentication

Endpoints with `x-access-level` above `anonymous` require authentication.
Credentials are the account username and an API key issued by `/api_keys.json`,
submitted as either HTTP Basic (username, API key) or the query/body parameters
`login` and `api_key`.

The `x-access-level` extension declares the minimum privilege level for an
operation: `anonymous`, `logged_in`, `member`, `janitor`, `moderator`, `admin`.

 * OpenAPI spec version: dadc1e4c50658851c0205e6ecbfa4723a976b0ab
 */

/**
 * A direct message between users.
 */
export interface Dmail {
  /** The body text of the DMail */
  body: string;
  /** When the DMail was created */
  created_at: Date;
  /** The ID of the sender */
  from_id: number;
  /** The sender's username */
  from_name?: string;
  /** The unique ID of the DMail */
  id: number;
  /** Whether the DMail has been deleted */
  is_deleted: boolean;
  /** Whether the DMail has been read */
  is_read: boolean;
  /** The ID of the user who owns this copy of the DMail */
  owner_id: number;
  /** The subject line of the DMail */
  title: string;
  /** The ID of the recipient */
  to_id: number;
  /** The recipient's username */
  to_name?: string;
  /** When the DMail was last updated */
  updated_at: Date;
}
