/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.

## Authentication

Endpoints with `x-access-level` above `anonymous` require authentication.
Credentials are the account username and an API key issued by `/api_keys.json`,
submitted as either HTTP Basic (username, API key) or the query/body parameters
`login` and `api_key`.

The `x-access-level` extension declares the minimum privilege level for an
operation: `anonymous`, `logged_in`, `member`, `janitor`, `moderator`, `admin`.

 * OpenAPI spec version: dadc1e4c50658851c0205e6ecbfa4723a976b0ab
 */
import type { GetEditHistoryType } from './getEditHistoryType';

export interface EditHistory {
  /** The unique ID of the edit history entry */
  id: number;
  /** The ID of the edited item */
  versionable_id: number;
  versionable_type: GetEditHistoryType;
  /** The ID of the user who made the edit */
  user_id?: number;
  /** The body content at this version */
  body: string;
  /**
   * The subject at this version (for forum posts)
   * @nullable
   */
  subject?: string | null;
  /** The version number */
  version: number;
  /**
   * The IP address of the editor
   * @nullable
   */
  ip_addr?: string | null;
  /** The time when this version was created */
  created_at: Date;
  /** The last time this version was updated */
  updated_at: Date;
}
