/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */
import type { ExceptionLogExtraParams } from './exceptionLogExtraParams';

/**
 * A recorded server exception.
 */
export interface ExceptionLog {
  /** The unique ID of the exception log */
  id: number;
  /** The class name of the raised exception */
  class_name: string;
  /** The application version the exception was raised on */
  version: string;
  /** The exception message */
  message: string;
  /** The newline-separated backtrace */
  trace: string;
  /** The public code shown to the user who hit the error */
  code: string;
  /**
   * Request context captured with the exception, including the host, filtered request params, referrer and user agent
   * @nullable
   */
  extra_params?: ExceptionLogExtraParams;
  /**
   * The ID of the user whose request raised the exception
   * @nullable
   */
  user_id?: number | null;
  /** When the exception was recorded */
  created_at: Date;
  /** When the exception log was last updated */
  updated_at: Date;
}
