/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

/**
 * Request context captured with the exception, including the host, filtered request params, referrer and user agent
 * @nullable
 */
export type ExceptionLogExtraParams = { [key: string]: unknown } | null;
