/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

/**
 * The file extension of the post's file
 */
export enum FileExt {
  jpg = 'jpg',
  png = 'png',
  gif = 'gif',
  webm = 'webm',
  mp4 = 'mp4',
  swf = 'swf',
  webp = 'webp',
}
