/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */
import type { FileExt } from './fileExt';

export interface File {
  /** The width of the file in pixels */
  width: number;
  /** The height of the file in pixels */
  height: number;
  ext: FileExt;
  /** The size of the file in bytes */
  size: number;
  /** The MD5 hash of the file */
  md5: string;
  /**
   * The URL of the file
   * @nullable
   */
  url: string | null;
}
