/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

export interface Flags {
  /** Whether the post is pending approval */
  pending: boolean;
  /** Whether the post is flagged */
  flagged: boolean;
  /** Whether notes on the post are locked */
  note_locked: boolean;
  /** Whether the status of the post is locked */
  status_locked: boolean;
  /** Whether the rating of the post is locked */
  rating_locked: boolean;
  /** Whether the post is deleted */
  deleted: boolean;
}
