/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

export interface ForumTopic {
  /** The unique ID of the forum topic */
  id: number;
  /** The ID of the user who created the topic */
  creator_id: number;
  /** The ID of the user who last updated the topic */
  updater_id: number;
  /** The topic title */
  title: string;
  /** The number of responses in the topic */
  response_count: number;
  /** Whether the topic is sticky */
  is_sticky: boolean;
  /** Whether the topic is locked */
  is_locked: boolean;
  /** Whether the topic is hidden */
  is_hidden: boolean;
  /** The time when the topic was created */
  created_at: Date;
  /** The last time the topic was updated */
  updated_at: Date;
  /** The forum category ID */
  category_id: number;
  /** The username of the topic creator */
  creator_name?: string;
  /** The username of the last updater */
  updater_name?: string;
}
