/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.

## Authentication

Endpoints with `x-access-level` above `anonymous` require authentication.
Credentials are the account username and an API key issued by `/api_keys.json`,
submitted as either HTTP Basic (username, API key) or the query/body parameters
`login` and `api_key`.

The `x-access-level` extension declares the minimum privilege level for an
operation: `anonymous`, `logged_in`, `member`, `janitor`, `moderator`, `admin`.

 * OpenAPI spec version: dadc1e4c50658851c0205e6ecbfa4723a976b0ab
 */

export interface ForumPost {
  /** The unique ID of the forum post */
  id: number;
  /** The ID of the forum topic this post belongs to */
  topic_id: number;
  /** The ID of the user who created the post */
  creator_id: number;
  /** The ID of the user who last updated the post */
  updater_id: number;
  /** The forum post body text */
  body: string;
  /** Whether the forum post is hidden */
  is_hidden: boolean;
  /** The time when the forum post was created */
  created_at: Date;
  /** The last time the forum post was updated */
  updated_at: Date;
  /**
   * The type of warning applied to the post
   * @nullable
   */
  warning_type?: number | null;
  /**
   * The ID of the user who applied the warning
   * @nullable
   */
  warning_user_id?: number | null;
  /** The username of the post creator */
  creator_name?: string;
  /** The username of the last updater */
  updater_name?: string;
}
