/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.

## Authentication

Endpoints with `x-access-level` above `anonymous` require authentication.
Credentials are the account username and an API key issued by `/api_keys.json`,
submitted as either HTTP Basic (username, API key) or the query/body parameters
`login` and `api_key`.

The `x-access-level` extension declares the minimum privilege level for an
operation: `anonymous`, `logged_in`, `member`, `janitor`, `moderator`, `admin`.

 * OpenAPI spec version: dadc1e4c50658851c0205e6ecbfa4723a976b0ab
 */

export interface ForumTopic {
  /** The unique ID of the forum topic */
  id: number;
  /** The ID of the user who created the topic */
  creator_id: number;
  /** The ID of the user who last updated the topic */
  updater_id: number;
  /** The topic title */
  title: string;
  /** The number of responses in the topic */
  response_count: number;
  /** Whether the topic is sticky */
  is_sticky: boolean;
  /** Whether the topic is locked */
  is_locked: boolean;
  /** Whether the topic is hidden */
  is_hidden: boolean;
  /** The time when the topic was created */
  created_at: Date;
  /** The last time the topic was updated */
  updated_at: Date;
  /** The forum category ID */
  category_id: number;
  /** The username of the topic creator */
  creator_name?: string;
  /** The username of the last updater */
  updater_name?: string;
}
