/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.

## Authentication

Endpoints with `x-access-level` above `anonymous` require authentication.
Credentials are the account username and an API key issued by `/api_keys.json`,
submitted as either HTTP Basic (username, API key) or the query/body parameters
`login` and `api_key`.

The `x-access-level` extension declares the minimum privilege level for an
operation: `anonymous`, `logged_in`, `member`, `janitor`, `moderator`, `admin`.

 * OpenAPI spec version: dadc1e4c50658851c0205e6ecbfa4723a976b0ab
 */
import type { ForumPostVoteScore } from './forumPostVoteScore';

export interface ForumPostVote {
  /** The time when the vote was cast */
  created_at: Date;
  /** The ID of the user who voted */
  creator_id: number;
  /** The username of the voter */
  creator_name?: string;
  /** The ID of the forum post that was voted on */
  forum_post_id: number;
  /** The unique ID of the forum post vote */
  id: number;
  /** The vote score (-1, 0, or 1) */
  score: ForumPostVoteScore;
  /** The last time the vote was updated */
  updated_at: Date;
}
