/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

export enum GetAvoidPostingsSearchOrder {
  artist_name = 'artist_name',
  artist_name_asc = 'artist_name_asc',
  artist_name_desc = 'artist_name_desc',
  created_at = 'created_at',
  updated_at = 'updated_at',
}
