/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.
 * OpenAPI spec version: 1.0.0
 */
import type { GetModActionsSearchAction } from './getModActionsSearchAction';

export type GetModActionsParams = {
/**
 * Filter by the name of the creator of the moderation action
 */
'search[creator_name]'?: string;
/**
 * Filter by the ID of the creator of the moderation action
 */
'search[creator_id]'?: number;
/**
 * Filter by the creation date of the moderation action
 */
'search[created_at]'?: string;
/**
 * Filter by the last update date of the moderation action
 */
'search[updated_at]'?: string;
/**
 * Filter by the ID of the moderation action
 */
'search[id]'?: string;
/**
 * Filter by the type of moderation action
 */
'search[action]'?: GetModActionsSearchAction;
};
