/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */
import type { GetPopularPostsScale } from './getPopularPostsScale';

export type GetPopularPostsParams = {
  /**
   * The date to get popular posts for (YYYY-MM-DD format)
   */
  date?: Date;
  /**
   * The time scale for popularity
   */
  scale?: GetPopularPostsScale;
};
