/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.

## Authentication

Endpoints with `x-access-level` above `anonymous` require authentication.
Credentials are the account username and an API key issued by `/api_keys.json`,
submitted as either HTTP Basic (username, API key) or the query/body parameters
`login` and `api_key`.

The `x-access-level` extension declares the minimum privilege level for an
operation: `anonymous`, `logged_in`, `member`, `janitor`, `moderator`, `admin`.

 * OpenAPI spec version: dadc1e4c50658851c0205e6ecbfa4723a976b0ab
 */
import type { GetPostFlagsSearchType } from './getPostFlagsSearchType';

export type GetPostFlagsParams = {
  /**
   * The page number to retrieve
   */
  page?: number;
  /**
   * The number of post flags to retrieve per page
   */
  limit?: number;
  /**
   * Filter post flags by matching reason text
   */
  'search[reason_matches]'?: string;
  /**
   * Filter post flags by matching post tags
   */
  'search[post_tags_match]'?: string;
  /**
   * Filter post flags by post ID
   */
  'search[post_id]'?: number;
  /**
   * Filter post flags by type (e.g., flag or deletion)
   */
  'search[type]'?: GetPostFlagsSearchType;
  /**
   * Filter post flags by resolution status
   */
  'search[is_resolved]'?: boolean;
  /**
   * Filter post flags by the creator's username
   */
  'search[creator_name]'?: string;
  /**
   * Filter post flags by creator ID
   */
  'search[creator_id]'?: number;
  /**
   * Filter post flags by creation date
   */
  'search[created_at]'?: string;
  /**
   * Filter post flags by last update date
   */
  'search[updated_at]'?: string;
  /**
   * Filter post flags by flag ID
   */
  'search[id]'?: string;
};
