/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

export type GetSimilarPostsByTagsParams = {
  /**
   * The number of recommendations to return. Clamped to 1-20. Defaults to 6.
   */
  limit?: number;
};
