/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

export enum GetTagImplicationsSearchOrder {
  id_desc = 'id_desc',
  id_asc = 'id_asc',
  status = 'status',
  created_at = 'created_at',
  updated_at = 'updated_at',
  name = 'name',
  tag_count = 'tag_count',
}
