/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

export enum GetTicketsSearchStatus {
  pending = 'pending',
  pending_unclaimed = 'pending_unclaimed',
  pending_claimed = 'pending_claimed',
  partial = 'partial',
  approved = 'approved',
}
