/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

export enum GetTagImplicationsSearchStatus {
  Approved = 'Approved',
  Active = 'Active',
  Pending = 'Pending',
  Deleted = 'Deleted',
  Retired = 'Retired',
  Processing = 'Processing',
  Queued = 'Queued',
}
