/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */
import type { GetTagImplicationsSearchOrder } from './getTagImplicationsSearchOrder';
import type { GetTagImplicationsSearchStatus } from './getTagImplicationsSearchStatus';

export type GetTagImplicationsParams = {
  /**
   * The page number to retrieve
   */
  page?: number;
  /**
   * The number of tag implications to retrieve per page
   */
  limit?: number;
  /**
   * Filter by matching names
   */
  'search[name_matches]'?: string;
  /**
   * Filter by the antecedent name of the implication
   */
  'search[antecedent_name]'?: string;
  /**
   * Filter by the consequent name of the implication
   */
  'search[consequent_name]'?: string;
  /**
   * Filter by the creator's username
   */
  'search[creator_name]'?: string;
  /**
   * Filter by the approver's username
   */
  'search[approver_name]'?: string;
  /**
   * Filter by the tag category of the antecedent tag
   */
  'search[antecedent_tag_category]'?: number;
  /**
   * Filter by the tag category of the consequent tag
   */
  'search[consequent_tag_category]'?: number;
  /**
   * Filter by the status of the tag implication
   */
  'search[status]'?: GetTagImplicationsSearchStatus;
  /**
   * Order the results by a specific field
   */
  'search[order]'?: GetTagImplicationsSearchOrder;
  /**
   * Filter by the creation date of the request
   */
  'search[created_at]'?: string;
  /**
   * Filter by the last update date of the request
   */
  'search[updated_at]'?: string;
};
