/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.

## Authentication

Endpoints with `x-access-level` above `anonymous` require authentication.
Credentials are the account username and an API key issued by `/api_keys.json`,
submitted as either HTTP Basic (username, API key) or the query/body parameters
`login` and `api_key`.

The `x-access-level` extension declares the minimum privilege level for an
operation: `anonymous`, `logged_in`, `member`, `janitor`, `moderator`, `admin`.

 * OpenAPI spec version: dadc1e4c50658851c0205e6ecbfa4723a976b0ab
 */
import type { GetTagImplicationsSearchOrder } from './getTagImplicationsSearchOrder';
import type { GetTagImplicationsSearchStatus } from './getTagImplicationsSearchStatus';

export type GetTagImplicationsParams = {
  /**
   * The page number to retrieve
   */
  page?: number;
  /**
   * The number of tag implications to retrieve per page
   */
  limit?: number;
  /**
   * Filter by matching names
   */
  'search[name_matches]'?: string;
  /**
   * Filter by the antecedent name of the implication
   */
  'search[antecedent_name]'?: string;
  /**
   * Filter by the consequent name of the implication
   */
  'search[consequent_name]'?: string;
  /**
   * Filter by the creator's username
   */
  'search[creator_name]'?: string;
  /**
   * Filter by the approver's username
   */
  'search[approver_name]'?: string;
  /**
   * Filter by the tag category of the antecedent tag
   */
  'search[antecedent_tag_category]'?: number;
  /**
   * Filter by the tag category of the consequent tag
   */
  'search[consequent_tag_category]'?: number;
  /**
   * Filter by the status of the tag implication
   */
  'search[status]'?: GetTagImplicationsSearchStatus;
  /**
   * Order the results by a specific field
   */
  'search[order]'?: GetTagImplicationsSearchOrder;
  /**
   * Filter by the creation date of the request
   */
  'search[created_at]'?: string;
  /**
   * Filter by the last update date of the request
   */
  'search[updated_at]'?: string;
};
