/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */
import type { GetTicketsSearchStatus } from './getTicketsSearchStatus';
import type { TicketQtype } from './ticketQtype';

export type GetTicketsParams = {
  /**
   * The page number to retrieve
   */
  page?: number;
  /**
   * The number of tickets to retrieve per page
   */
  limit?: number;
  /**
   * Filter by the creation date of the ticket
   */
  'search[created_at]'?: string;
  /**
   * Filter by the last update date of the ticket
   */
  'search[updated_at]'?: string;
  /**
   * Filter by ticket ID
   */
  'search[id]'?: string;
  /**
   * Filter by the creator's username
   */
  'search[creator_name]'?: string;
  /**
   * Filter by the accused user's username
   */
  'search[accused_name]'?: string;
  /**
   * Filter by the claimant's username
   */
  'search[claimant_name]'?: string;
  /**
   * Filter by the reason for the ticket
   */
  'search[reason]'?: string;
  /**
   * Filter by the type of the ticket (e.g., user, comment, post)
   */
  'search[qtype]'?: TicketQtype;
  /**
   * Filter by the status of the ticket
   */
  'search[status]'?: GetTicketsSearchStatus;
  /**
   * Filter by the reported content ID
   */
  'search[disp_id]'?: number;
};
