/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

/**
 * Matched against the upload status with SQL `LIKE`, where `*` is the
wildcard. `completed`, `processing` and `pending` match exactly. The
duplicate and error statuses carry a suffix (`duplicate: <post_id>`,
`error: <message>`), so matching those needs a wildcard, as in
`duplicate*`.

 */
export type GetUploadsSearchStatus = string;
