/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.

## Authentication

Endpoints with `x-access-level` above `anonymous` require authentication.
Credentials are the account username and an API key issued by `/api_keys.json`,
submitted as either HTTP Basic (username, API key) or the query/body parameters
`login` and `api_key`.

The `x-access-level` extension declares the minimum privilege level for an
operation: `anonymous`, `logged_in`, `member`, `janitor`, `moderator`, `admin`.

 * OpenAPI spec version: dadc1e4c50658851c0205e6ecbfa4723a976b0ab
 */

/**
 * A site mascot.
 */
export interface Mascot {
  /** The unique ID of the mascot */
  id: number;
  /** The ID of the user who created the mascot */
  creator_id: number;
  /** The display name of the mascot */
  display_name: string;
  /** The MD5 hash of the mascot image */
  md5: string;
  /** The file extension of the mascot image */
  file_ext: string;
  /** Background color (hex) */
  background_color: string;
  /** Foreground color (hex) */
  foreground_color: string;
  /** URL to the artist's page */
  artist_url: string;
  /** Name of the artist */
  artist_name: string;
  /** Whether the mascot is active */
  active: boolean;
  /** Sites the mascot is available on */
  available_on?: string[];
  /** Whether the mascot is layered */
  is_layered?: boolean;
  /** URL path to the mascot image */
  url_path?: string;
  /** When the mascot was created */
  created_at: Date;
  /** When the mascot was last updated */
  updated_at: Date;
}
