/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

/**
 * A site mascot.
 */
export interface Mascot {
  /** The unique ID of the mascot */
  id: number;
  /** The ID of the user who created the mascot */
  creator_id: number;
  /** The display name of the mascot */
  display_name: string;
  /** The MD5 hash of the mascot image */
  md5: string;
  /** The file extension of the mascot image */
  file_ext: string;
  /** Background color (hex) */
  background_color: string;
  /** Foreground color (hex) */
  foreground_color: string;
  /** URL to the artist's page */
  artist_url: string;
  /** Name of the artist */
  artist_name: string;
  /** Whether the mascot is active */
  active: boolean;
  /** Sites the mascot is available on */
  available_on?: string[];
  /** Whether the mascot is layered */
  is_layered?: boolean;
  /** URL path to the mascot image */
  url_path?: string;
  /** When the mascot was created */
  created_at: Date;
  /** When the mascot was last updated */
  updated_at: Date;
}
