/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.
 * OpenAPI spec version: 1.0.0
 */
import type { ModActionAction } from './modActionAction';
import type { ModActionValues } from './modActionValues';

/**
 * A moderation action representing administrative actions taken on the platform.
 */
export interface ModAction {
  /** The type of moderation action performed */
  action: ModActionAction;
  /** The timestamp when the moderation action was created */
  created_at: Date;
  /** The ID of the user who performed the moderation action */
  creator_id: number;
  /** The unique ID of the moderation action */
  id: number;
  /** The timestamp when the moderation action was last updated */
  updated_at: Date;
  /** Additional details or parameters related to the moderation action */
  values: ModActionValues;
}
