/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

/**
 * A news update displayed on the site.
 */
export interface NewsUpdate {
  /** The unique ID of the news update */
  id: number;
  /** The news message content */
  message: string;
  /** The ID of the user who created the update */
  creator_id: number;
  /** The ID of the user who last updated it */
  updater_id: number;
  /** When the news update was created */
  created_at: Date;
  /** When the news update was last updated */
  updated_at: Date;
}
