/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.

## Authentication

Endpoints with `x-access-level` above `anonymous` require authentication.
Credentials are the account username and an API key issued by `/api_keys.json`,
submitted as either HTTP Basic (username, API key) or the query/body parameters
`login` and `api_key`.

The `x-access-level` extension declares the minimum privilege level for an
operation: `anonymous`, `logged_in`, `member`, `janitor`, `moderator`, `admin`.

 * OpenAPI spec version: dadc1e4c50658851c0205e6ecbfa4723a976b0ab
 */

/**
 * A news update displayed on the site.
 */
export interface NewsUpdate {
  /** The unique ID of the news update */
  id: number;
  /** The news message content */
  message: string;
  /** The ID of the user who created the update */
  creator_id: number;
  /** The ID of the user who last updated it */
  updater_id: number;
  /** When the news update was created */
  created_at: Date;
  /** When the news update was last updated */
  updated_at: Date;
}
