/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

export interface NoteVersion {
  /** The unique ID of the note version */
  id: number;
  /** The ID of the note */
  note_id: number;
  /** The ID of the post the note is on */
  post_id: number;
  /** The ID of the user who made this version */
  updater_id: number;
  /** X coordinate at this version */
  x: number;
  /** Y coordinate at this version */
  y: number;
  /** Width at this version */
  width: number;
  /** Height at this version */
  height: number;
  /** Whether the note was active at this version */
  is_active: boolean;
  /** The body text at this version */
  body: string;
  /** The version number */
  version: number;
  /** When this version was created */
  created_at: Date;
  /** When this version was last updated */
  updated_at: Date;
}
