/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

export interface PoolVersion {
  /** The unique ID of the pool version */
  id: number;
  /** The ID of the pool */
  pool_id: number;
  /** The full ordered list of post IDs at this version */
  post_ids: number[];
  /** Post IDs added in this version */
  added_post_ids: number[];
  /** Post IDs removed in this version */
  removed_post_ids: number[];
  /** The ID of the user who made this version */
  updater_id?: number;
  /**
   * The pool description at this version
   * @nullable
   */
  description?: string | null;
  /** Whether the description was changed in this version */
  description_changed?: boolean;
  /**
   * The pool name at this version
   * @nullable
   */
  name?: string | null;
  /** Whether the name was changed in this version */
  name_changed?: boolean;
  /** Whether the pool was active at this version */
  is_active?: boolean;
  /**
   * The pool category at this version
   * @nullable
   */
  category?: string | null;
  /** The version number */
  version: number;
  /** When this version was created */
  created_at: Date;
  /** When this version was last updated */
  updated_at: Date;
}
