/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.

## Authentication

Endpoints with `x-access-level` above `anonymous` require authentication.
Credentials are the account username and an API key issued by `/api_keys.json`,
submitted as either HTTP Basic (username, API key) or the query/body parameters
`login` and `api_key`.

The `x-access-level` extension declares the minimum privilege level for an
operation: `anonymous`, `logged_in`, `member`, `janitor`, `moderator`, `admin`.

 * OpenAPI spec version: dadc1e4c50658851c0205e6ecbfa4723a976b0ab
 */

export interface PoolVersion {
  /** The unique ID of the pool version */
  id: number;
  /** The ID of the pool */
  pool_id: number;
  /** The full ordered list of post IDs at this version */
  post_ids: number[];
  /** Post IDs added in this version */
  added_post_ids: number[];
  /** Post IDs removed in this version */
  removed_post_ids: number[];
  /** The ID of the user who made this version */
  updater_id?: number;
  /**
   * The pool description at this version
   * @nullable
   */
  description?: string | null;
  /** Whether the description was changed in this version */
  description_changed?: boolean;
  /**
   * The pool name at this version
   * @nullable
   */
  name?: string | null;
  /** Whether the name was changed in this version */
  name_changed?: boolean;
  /** Whether the pool was active at this version */
  is_active?: boolean;
  /**
   * The pool category at this version
   * @nullable
   */
  category?: string | null;
  /** The version number */
  version: number;
  /** When this version was created */
  created_at: Date;
  /** When this version was last updated */
  updated_at: Date;
}
