/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.

## Authentication

Endpoints with `x-access-level` above `anonymous` require authentication.
Credentials are the account username and an API key issued by `/api_keys.json`,
submitted as either HTTP Basic (username, API key) or the query/body parameters
`login` and `api_key`.

The `x-access-level` extension declares the minimum privilege level for an
operation: `anonymous`, `logged_in`, `member`, `janitor`, `moderator`, `admin`.

 * OpenAPI spec version: dadc1e4c50658851c0205e6ecbfa4723a976b0ab
 */
import type { PoolCategory } from './poolCategory';

export interface Pool {
  /** The pool category */
  category: PoolCategory;
  /** When the pool was created */
  created_at: Date;
  /** The ID of the pool creator */
  creator_id: number;
  /** The username of the pool creator */
  creator_name?: string;
  /** The pool description */
  description?: string;
  /** The unique ID of the pool */
  id: number;
  /** Whether the pool is active */
  is_active: boolean;
  /** The name of the pool */
  name: string;
  /** The number of posts in the pool */
  post_count?: number;
  /** Ordered array of post IDs in the pool */
  post_ids: number[];
  /** When the pool was last updated */
  updated_at: Date;
}
