/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */
import type { PostFilesMeta } from './postFilesMeta';
import type { PostFilesOriginal } from './postFilesOriginal';
import type { PostFilesSample } from './postFilesSample';
import type { PostFilesVideo } from './postFilesVideo';

/**
 * File information for a v2 Post payload.
 */
export interface PostFiles {
  meta: PostFilesMeta;
  original: PostFilesOriginal;
  preview: PostFilesSample;
  sample: PostFilesSample;
  video?: PostFilesVideo;
}
