/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

/**
 * A vote on a post.
 */
export interface PostVote {
  /** The unique ID of the vote */
  id: number;
  /** The ID of the voted post */
  post_id: number;
  /** The ID of the voting user */
  user_id: number;
  /** The vote score (1, 0, or -1) */
  score: number;
  /** When the vote was cast */
  created_at: Date;
  /** When the vote was last updated */
  updated_at: Date;
}
