/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */
import type { PostFlagType } from './postFlagType';

/**
 * A post flag object representing a user's flag or deletion of a post.
 */
export interface PostFlag {
  /** The unique ID of the post flag */
  id: number;
  /** The timestamp when the post flag was created */
  created_at: Date;
  /** The ID of the post that the flag is related to */
  post_id: number;
  /** The reason for the flag or deletion request */
  reason: string;
  /** The ID of the user who created the flag or deletion request */
  creator_id?: number;
  /** Whether the flag has been resolved */
  is_resolved: boolean;
  /** The timestamp when the post flag was last updated */
  updated_at: Date;
  /** Whether the flag is a deletion request */
  is_deletion: boolean;
  type: PostFlagType;
  /**
   * The configured flag reason this flag was raised under
   * @nullable
   */
  reason_name?: string | null;
  /** Whether the flag requires a parent post ID before it can be resolved */
  needs_parent_id: boolean;
  /** Whether the flag requires a staff-supplied reason */
  needs_staff_reason: boolean;
  /**
   * Additional explanation regarding the flag
   * @nullable
   */
  note?: string | null;
}
