/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

export interface PostHas {
  parent: boolean;
  children: boolean;
  active_children: boolean;
  notes: boolean;
  sample: boolean;
}
