/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.

## Authentication

Endpoints with `x-access-level` above `anonymous` require authentication.
Credentials are the account username and an API key issued by `/api_keys.json`,
submitted as either HTTP Basic (username, API key) or the query/body parameters
`login` and `api_key`.

The `x-access-level` extension declares the minimum privilege level for an
operation: `anonymous`, `logged_in`, `member`, `janitor`, `moderator`, `admin`.

 * OpenAPI spec version: dadc1e4c50658851c0205e6ecbfa4723a976b0ab
 */

/**
 * A vote on a post.
 */
export interface PostVote {
  /** When the vote was cast */
  created_at: Date;
  /** The unique ID of the vote */
  id: number;
  /** The ID of the voted post */
  post_id: number;
  /** The vote score (1, 0, or -1) */
  score: number;
  /** When the vote was last updated */
  updated_at: Date;
  /** The ID of the voting user */
  user_id: number;
}
