/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

export interface PostSet {
  /** The unique ID of the post set */
  id: number;
  /** The name of the post set */
  name: string;
  /** The short name of the post set */
  shortname: string;
  /** The post set description */
  description?: string;
  /** Whether the post set is publicly visible */
  is_public: boolean;
  /** Whether to transfer favorites on delete */
  transfer_on_delete?: boolean;
  /** The ID of the set creator */
  creator_id: number;
  /** Ordered array of post IDs in the set */
  post_ids: number[];
  /** The number of posts in the set */
  post_count: number;
  /** When the post set was created */
  created_at: Date;
  /** When the post set was last updated */
  updated_at: Date;
}
