/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */
import type { PostRecommendationResult } from './postRecommendationResult';
import type { ThumbnailPost } from './thumbnailPost';

/**
 * Posts recommended for a given post.
 */
export interface PostRecommendations {
  /** The ID of the post the recommendations were made for */
  post_id: number;
  /** The recommendation model that produced the results (e.g. "os.artist", "os.tags") */
  model_version: string;
  /** The recommended post IDs with their scores */
  results: PostRecommendationResult[];
  /** Thumbnail payloads for the recommended posts */
  post_data: ThumbnailPost[];
}
