/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */
import type { PostStatsScore } from './postStatsScore';

export interface PostStats {
  score: PostStatsScore;
  fav_count: number;
  is_favorited: boolean;
  /** The requesting user's vote on the post, `1`, `-1`, or `0` when they have not voted or are not logged in */
  vote: number;
  comment_count: number;
  /** The post's hotness score */
  hotness: number;
}
