/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */
import type { PostFiles } from './postFiles';
import type { PostFlags } from './postFlags';
import type { PostHas } from './postHas';
import type { PostRating } from './postRating';
import type { PostRelationships } from './postRelationships';
import type { PostStats } from './postStats';

/**
 * Common fields shared by the v2 basic and extended Post formats.
 */
export interface PostBase {
  id: number;
  created_at: Date;
  updated_at: Date;
  change_seq: number;
  files: PostFiles;
  uploader_id: number;
  uploader_name: string;
  /** @nullable */
  approver_id: number | null;
  stats: PostStats;
  flags: PostFlags;
  has: PostHas;
  relationships: PostRelationships;
  pools: number[];
  rating: PostRating;
  locked_tags: string[];
  sources: string[];
  description: string;
}
