/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */
import type { PostAllOf } from './postAllOf';
import type { PostBase } from './postBase';

/**
 * Extended v2 Post payload (`v2=true`, `mode=extended`). Tags are grouped by category name.
 */
export type Post = PostBase & PostAllOf;
