/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

export interface Preview {
  /** The width of the preview in pixels */
  width: number;
  /** The height of the preview in pixels */
  height: number;
  /**
   * The URL of the preview image
   * @nullable
   */
  url: string | null;
  /**
   * The URL of the WebP preview image
   * @nullable
   */
  alt?: string | null;
}
