/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.

## Authentication

Endpoints with `x-access-level` above `anonymous` require authentication.
Credentials are the account username and an API key issued by `/api_keys.json`,
submitted as either HTTP Basic (username, API key) or the query/body parameters
`login` and `api_key`.

The `x-access-level` extension declares the minimum privilege level for an
operation: `anonymous`, `logged_in`, `member`, `janitor`, `moderator`, `admin`.

 * OpenAPI spec version: dadc1e4c50658851c0205e6ecbfa4723a976b0ab
 */

export interface Relationships {
  /** An array of child post IDs */
  children: number[];
  /** Whether the post has any active child posts */
  has_active_children: boolean;
  /** Whether the post has any child posts */
  has_children: boolean;
  /**
   * The ID of the parent post, if applicable
   * @nullable
   */
  parent_id?: number | null;
}
