/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

/**
 * Related tags for a given query.
 */
export interface RelatedTag {
  /** The query tag */
  query?: string;
  /**
   * The category ID filter
   * @nullable
   */
  category?: number | null;
  /** Array of related tag pairs */
  tags?: string[][];
  /** Tags found on the wiki page */
  wiki_page_tags?: string[];
}
