/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */
import type { ResolvePostFlagApproval } from './resolvePostFlagApproval';

export type ResolvePostFlagParams = {
  /**
   * Set to "approve" to also approve the post
   */
  approval?: ResolvePostFlagApproval;
};
