/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

/**
 * Sample versions keyed by name
 */
export interface SampleAlternatesSamples {
  [key: string]: {
    /** @nullable */
    url?: string | null;
    width?: number;
    height?: number;
  };
}
