/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.

## Authentication

Endpoints with `x-access-level` above `anonymous` require authentication.
Credentials are the account username and an API key issued by `/api_keys.json`,
submitted as either HTTP Basic (username, API key) or the query/body parameters
`login` and `api_key`.

The `x-access-level` extension declares the minimum privilege level for an
operation: `anonymous`, `logged_in`, `member`, `janitor`, `moderator`, `admin`.

 * OpenAPI spec version: dadc1e4c50658851c0205e6ecbfa4723a976b0ab
 */
import type { SampleAlternates } from './sampleAlternates';

export interface Sample {
  /** Whether the sample exists */
  has: boolean;
  /** The height of the sample image in pixels */
  height: number;
  /** The width of the sample image in pixels */
  width: number;
  /** The URL of the sample image */
  url: string;
  /**
   * The URL of the WebP sample image
   * @nullable
   */
  alt?: string | null;
  alternates?: SampleAlternates;
}
