/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

export interface Score {
  /** The number of upvotes on the post */
  up: number;
  /** The number of downvotes on the post */
  down: number;
  /** The total score (upvotes minus downvotes) */
  total: number;
}
