/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

export enum SearchPostSetsSearchOrder {
  name = 'name',
  shortname = 'shortname',
  post_count = 'post_count',
  created_at = 'created_at',
  updated_at = 'updated_at',
}
