/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

/**
 * The number of times a tag was searched for during a given hour.
 */
export interface SearchTrendHourly {
  /** The tag name */
  tag: string;
  /** The number of searches recorded for the hour */
  count: number;
  /** The start of the hour the searches were recorded in */
  hour: Date;
  /** Whether the record has been rolled up into the daily totals */
  processed: boolean;
}
