/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

/**
 * A tag pattern excluded from search trend recording.
 */
export interface SearchTrendBlacklist {
  /** The unique ID of the blacklist entry */
  id: number;
  /** The blacklisted tag pattern, supporting the `*` and `?` globs */
  tag: string;
  /** The reason for blacklisting */
  reason: string;
  /** The ID of the user who created the entry */
  creator_id: number;
  /** When the entry was created */
  created_at: Date;
  /** When the entry was last updated */
  updated_at: Date;
}
