/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

/**
 * A staff-only note on a user.
 */
export interface StaffNote {
  /** The unique ID of the staff note */
  id: number;
  /** The ID of the user the note is about */
  user_id: number;
  /** The ID of the staff member who created the note */
  creator_id: number;
  /** The ID of the staff member who last updated the note */
  updater_id?: number;
  /** The body text of the staff note */
  body: string;
  /** Whether the staff note has been deleted */
  is_deleted: boolean;
  /** When the staff note was created */
  created_at: Date;
  /** When the staff note was last updated */
  updated_at: Date;
}
