/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */
import type { StaffDeletePostBodyCommit } from './staffDeletePostBodyCommit';

export interface StaffDeletePostBody {
  /** The reason for deleting the post */
  reason: string;
  commit: StaffDeletePostBodyCommit;
  /** Set if the deletion originates from a flag */
  from_flag?: string;
  /** Copy sources to the parent post */
  copy_sources?: boolean;
  /** Copy tags to the parent post */
  copy_tags?: boolean;
  /** Move favorites and post sets to the parent post */
  move_favorites?: boolean;
}
