/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

/**
 * A staff-only wiki page.
 */
export interface StaffWiki {
  /** The unique ID of the staff wiki page */
  id: number;
  /** The ID of the user who created the page */
  creator_id: number;
  /** The ID of the user who last updated the page */
  updater_id: number;
  /**
   * The ID of the user currently claiming the page
   * @nullable
   */
  claimant_id?: number | null;
  /** The title of the page */
  title: string;
  /** The DText body of the page */
  body: string;
  /** When the page was created */
  created_at: Date;
  /** When the page was last updated */
  updated_at: Date;
}
