/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.

## Authentication

Endpoints with `x-access-level` above `anonymous` require authentication.
Credentials are the account username and an API key issued by `/api_keys.json`,
submitted as either HTTP Basic (username, API key) or the query/body parameters
`login` and `api_key`.

The `x-access-level` extension declares the minimum privilege level for an
operation: `anonymous`, `logged_in`, `member`, `janitor`, `moderator`, `admin`.

 * OpenAPI spec version: dadc1e4c50658851c0205e6ecbfa4723a976b0ab
 */

/**
 * A staff-only note on a user.
 */
export interface StaffNote {
  /** The unique ID of the staff note */
  id: number;
  /** The ID of the user the note is about */
  user_id: number;
  /** The ID of the staff member who created the note */
  creator_id: number;
  /** The ID of the staff member who last updated the note */
  updater_id?: number;
  /** The body text of the staff note */
  body: string;
  /** Whether the staff note has been deleted */
  is_deleted: boolean;
  /** When the staff note was created */
  created_at: Date;
  /** When the staff note was last updated */
  updated_at: Date;
}
