/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

/**
 * A past revision of a staff wiki page.
 */
export interface StaffWikiVersion {
  /** The unique ID of the version */
  id: number;
  /** The ID of the staff wiki page this version belongs to */
  staff_wiki_id: number;
  /** The ID of the user who made the edit */
  updater_id: number;
  /**
   * The ID of the user claiming the page at the time of the edit
   * @nullable
   */
  claimant_id?: number | null;
  /** The title of the page in this version */
  title: string;
  /** The DText body of the page in this version */
  body: string;
  /** When the version was created */
  created_at: Date;
  /** When the version was last updated */
  updated_at: Date;
}
