/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

/**
 * A snapshot of site-wide statistics. Empty until the snapshot job has run.
 */
export interface Stats {
  /** When the oldest post was created */
  started?: Date;
  /** The highest post ID */
  total_posts?: number;
  /** The number of active posts */
  active_posts?: number;
  /** The number of deleted posts */
  deleted_posts?: number;
  /** The sum of active and deleted posts */
  existing_posts?: number;
  /** The number of posts that no longer exist */
  destroyed_posts?: number;
  /** The number of post votes */
  total_votes?: number;
  /** The number of notes */
  total_notes?: number;
  /** The number of favorites */
  total_favorites?: number;
  /** The number of pools */
  total_pools?: number;
  /** The number of public post sets */
  public_sets?: number;
  /** The number of private post sets */
  private_sets?: number;
  /** The sum of public and private post sets */
  total_sets?: number;
  /** The average number of posts in a pool */
  average_posts_per_pool?: number;
  /** The average number of posts in a post set */
  average_posts_per_set?: number;
  /** The number of safe rated posts */
  safe_posts?: number;
  /** The number of questionable rated posts */
  questionable_posts?: number;
  /** The number of explicit rated posts */
  explicit_posts?: number;
  /** The number of JPEG posts */
  jpg_posts?: number;
  /** The number of PNG posts */
  png_posts?: number;
  /** The number of WebP posts */
  webp_posts?: number;
  /** The number of GIF posts */
  gif_posts?: number;
  /** The number of SWF posts */
  swf_posts?: number;
  /** The number of WebM posts */
  webm_posts?: number;
  /** The number of MP4 posts */
  mp4_posts?: number;
  /** The average post file size, in bytes */
  average_file_size?: number;
  /** The combined size of all post files, in bytes */
  total_file_size?: number;
  /** The average number of posts uploaded per day */
  average_posts_per_day?: number;
  /** The number of users */
  total_users?: number;
  /** The number of users at the Anonymous level */
  anonymous_users?: number;
  /** The number of users at the Blocked level */
  blocked_users?: number;
  /** The number of users at the Member level */
  member_users?: number;
  /** The number of users at the Privileged level */
  privileged_users?: number;
  /** The number of users at the Former Staff level */
  former_staff_users?: number;
  /** The number of users at the Staff level */
  staff_users?: number;
  /** The number of users at the Janitor level */
  janitor_users?: number;
  /** The number of users at the Moderator level */
  moderator_users?: number;
  /** The number of users at the Admin level */
  admin_users?: number;
  /** The number of users who have not verified their email */
  unactivated_users?: number;
  /** The highest DMail ID halved, since each DMail is stored twice */
  total_dmails?: number;
  /** The average number of accounts registered per day */
  average_registrations_per_day?: number;
  /** The number of users who logged in within the last three months */
  active_users?: number;
  /** The highest comment ID */
  total_comments?: number;
  /** The number of visible comments */
  active_comments?: number;
  /** The number of hidden comments */
  hidden_comments?: number;
  /** The number of comments that no longer exist */
  deleted_comments?: number;
  /** The average number of comments posted per day */
  average_comments_per_day?: number;
  /** The number of forum topics */
  total_forum_threads?: number;
  /** The highest forum post ID */
  total_forum_posts?: number;
  /** The average number of posts in a forum topic */
  average_posts_per_thread?: number;
  /** The average number of forum posts made per day */
  average_forum_posts_per_day?: number;
  /** The highest blip ID */
  total_blips?: number;
  /** The number of visible blips */
  active_blips?: number;
  /** The number of deleted blips */
  deleted_blips?: number;
  /** The number of blips that no longer exist */
  destroyed_blips?: number;
  /** The average number of blips posted per day */
  average_blips_per_day?: number;
  /** The number of tags */
  total_tags?: number;
  /** The number of general tags */
  general_tags?: number;
  /** The number of species tags */
  species_tags?: number;
  /** The number of character tags */
  character_tags?: number;
  /** The number of copyright tags */
  copyright_tags?: number;
  /** The number of artist tags */
  artist_tags?: number;
  /** The number of contributor tags */
  contributor_tags?: number;
  /** The number of invalid tags */
  invalid_tags?: number;
  /** The number of lore tags */
  lore_tags?: number;
  /** The number of meta tags */
  meta_tags?: number;
  /** When the snapshot was generated */
  updated_at?: Date;
}
