/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.

## Authentication

Endpoints with `x-access-level` above `anonymous` require authentication.
Credentials are the account username and an API key issued by `/api_keys.json`,
submitted as either HTTP Basic (username, API key) or the query/body parameters
`login` and `api_key`.

The `x-access-level` extension declares the minimum privilege level for an
operation: `anonymous`, `logged_in`, `member`, `janitor`, `moderator`, `admin`.

 * OpenAPI spec version: dadc1e4c50658851c0205e6ecbfa4723a976b0ab
 */

export interface Tag {
  /** The unique ID of the tag */
  id: number;
  /** The name of the tag */
  name: string;
  /** The number of posts with this tag */
  post_count: number;
  /** The category ID of the tag */
  category: number;
  /**
   * Space-separated related tags with counts
   * @nullable
   */
  related_tags?: string | null;
  /**
   * When related tags were last updated
   * @nullable
   */
  related_tags_updated_at?: Date | null;
  /** Whether the tag category is locked */
  is_locked: boolean;
  /** When the tag was created */
  created_at: Date;
  /** When the tag was last updated */
  updated_at: Date;
}
