/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

export interface Tag {
  /** The unique ID of the tag */
  id: number;
  /** The name of the tag */
  name: string;
  /** The number of posts with this tag */
  post_count: number;
  /** The category ID of the tag */
  category: number;
  /**
   * Space-separated related tags with counts
   * @nullable
   */
  related_tags?: string | null;
  /**
   * When related tags were last updated
   * @nullable
   */
  related_tags_updated_at?: Date | null;
  /** Whether the tag category is locked */
  is_locked: boolean;
  /** When the tag was created */
  created_at: Date;
  /** When the tag was last updated */
  updated_at: Date;
}
