/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */
import type { TagAliasStatus } from './tagAliasStatus';

export interface TagAlias {
  /** The unique ID of the tag alias */
  id: number;
  /** The name of the antecedent tag */
  antecedent_name: string;
  /** The name of the consequent tag */
  consequent_name: string;
  status: TagAliasStatus;
  /** The timestamp when the tag alias was created */
  created_at: Date;
  /** The timestamp when the tag alias was last updated */
  updated_at: Date;
  /** The reason for creating the tag alias */
  reason?: string;
  /** The ID of the user who created the tag alias */
  creator_id: number;
  /**
   * The ID of the user who approved the tag alias, if applicable
   * @nullable
   */
  approver_id?: number | null;
  /** The ID of the associated forum post */
  forum_post_id?: number;
  /** The ID of the associated forum topic */
  forum_topic_id?: number;
  /** The number of posts associated with the tag alias */
  post_count?: number;
}
