/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.
 * OpenAPI spec version: 1.0.0
 */

/**
 * The current status of the tag alias
 */
export enum TagAliasStatus {
  approved = 'approved',
  active = 'active',
  pending = 'pending',
  deleted = 'deleted',
  retired = 'retired',
  processing = 'processing',
  queued = 'queued',
}
