/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */
import type { Tag } from './tag';

export interface TagCorrection {
  /** The post count currently stored on the tag */
  post_count: number;
  /** The post count reported by the search index */
  real_post_count: number;
  /** The category ID currently stored on the tag */
  category: number;
  /**
   * The cached category ID for the tag, null when the cache entry has expired
   * @nullable
   */
  category_cache: number | null;
  tag: Tag;
}
