/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.

## Authentication

Endpoints with `x-access-level` above `anonymous` require authentication.
Credentials are the account username and an API key issued by `/api_keys.json`,
submitted as either HTTP Basic (username, API key) or the query/body parameters
`login` and `api_key`.

The `x-access-level` extension declares the minimum privilege level for an
operation: `anonymous`, `logged_in`, `member`, `janitor`, `moderator`, `admin`.

 * OpenAPI spec version: dadc1e4c50658851c0205e6ecbfa4723a976b0ab
 */
import type { TagImplicationStatus } from './tagImplicationStatus';

export interface TagImplication {
  /** The unique ID of the tag implication */
  id: number;
  /** The name of the antecedent tag */
  antecedent_name: string;
  /** The name of the consequent tag */
  consequent_name: string;
  status: TagImplicationStatus;
  /** The timestamp when the tag implication was created */
  created_at: Date;
  /** The timestamp when the tag implication was last updated */
  updated_at: Date;
  /** The reason for creating the tag implication */
  reason?: string;
  /** The ID of the user who created the tag implication */
  creator_id: number;
  /**
   * The ID of the user who approved the tag implication, if applicable
   * @nullable
   */
  approver_id?: number | null;
  /** The ID of the associated forum post */
  forum_post_id?: number;
  /** The ID of the associated forum topic */
  forum_topic_id?: number;
  /** A list of descendant tag names derived from this implication */
  descendant_names?: string[];
}
