/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */
import type { TagImplicationStatus } from './tagImplicationStatus';

export interface TagImplication {
  /** The unique ID of the tag implication */
  id: number;
  /** The name of the antecedent tag */
  antecedent_name: string;
  /** The name of the consequent tag */
  consequent_name: string;
  status: TagImplicationStatus;
  /** The timestamp when the tag implication was created */
  created_at: Date;
  /** The timestamp when the tag implication was last updated */
  updated_at: Date;
  /** The reason for creating the tag implication */
  reason?: string;
  /** The ID of the user who created the tag implication */
  creator_id: number;
  /**
   * The ID of the user who approved the tag implication, if applicable
   * @nullable
   */
  approver_id?: number | null;
  /** The ID of the associated forum post */
  forum_post_id?: number;
  /** The ID of the associated forum topic */
  forum_topic_id?: number;
  /** A list of descendant tag names derived from this implication */
  descendant_names?: string[];
}
