/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

export interface TagTypeVersion {
  /** The unique ID of the tag type version */
  id: number;
  /** The ID of the tag that was changed */
  tag_id: number;
  /** The previous category ID */
  old_type: number;
  /** The new category ID */
  new_type: number;
  /** Whether the tag was locked at time of change */
  is_locked: boolean;
  /** The ID of the user who made the change */
  creator_id: number;
  /** When the change was made */
  created_at: Date;
  /** When the record was last updated */
  updated_at: Date;
}
