/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.

## Authentication

Endpoints with `x-access-level` above `anonymous` require authentication.
Credentials are the account username and an API key issued by `/api_keys.json`,
submitted as either HTTP Basic (username, API key) or the query/body parameters
`login` and `api_key`.

The `x-access-level` extension declares the minimum privilege level for an
operation: `anonymous`, `logged_in`, `member`, `janitor`, `moderator`, `admin`.

 * OpenAPI spec version: dadc1e4c50658851c0205e6ecbfa4723a976b0ab
 */
import type { UpdateTicketBodyTicketStatus } from './updateTicketBodyTicketStatus';

export type UpdateTicketBody = {
  /** The response to the ticket */
  'ticket[response]'?: string;
  /** The new status of the ticket */
  'ticket[status]'?: UpdateTicketBodyTicketStatus;
  /** The type of record to apply if the ticket content is warnable */
  'ticket[record_type]'?: string;
  /** Whether to send a DMail notification about the update */
  'ticket[send_update_dmail]'?: boolean;
  /** Force claiming the ticket even if already claimed by another user */
  force_claim?: boolean;
};
