/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */
import type { AppealStatus } from './appealStatus';

export interface UpdateAppealBody {
  /** The response to the appeal */
  'appeal[response]'?: string;
  'appeal[status]'?: AppealStatus;
  /** Whether to send a DMail notification about the update */
  'appeal[send_update_dmail]'?: boolean;
  /** Force claiming the appeal even if already claimed by another user */
  force_claim?: boolean;
}
