/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */
import type { UpdateTakedownBodyTakedownPosts } from './updateTakedownBodyTakedownPosts';

export interface UpdateTakedownBody {
  /** Staff notes for the takedown */
  'takedown[notes]'?: string;
  /** Whether to hide the reason */
  'takedown[reason_hidden]'?: boolean;
  takedown_posts?: UpdateTakedownBodyTakedownPosts;
  /** Whether to process the takedown */
  process_takedown?: boolean;
  /** Reason for deleting posts */
  delete_reason?: string;
}
