/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

export interface UpdateTagAliasBody {
  /** The name of the antecedent tag, only applied while the alias is pending */
  'tag_alias[antecedent_name]'?: string;
  /** The name of the consequent tag, only applied while the alias is pending */
  'tag_alias[consequent_name]'?: string;
  /** The ID of the forum topic to link to */
  'tag_alias[forum_topic_id]'?: number;
}
