/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */
import type { UserFeedbackCategory } from './userFeedbackCategory';

export interface UpdateUserFeedbackBodyUserFeedback {
  /** New feedback body (DText supported) */
  body?: string;
  category?: UserFeedbackCategory;
  /** Send DMail notification to the user about the update */
  send_update_dmail?: boolean;
}
