/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

export interface UpdateStaffFileBodyStaffFile {
  /** The display title. Cleared titles fall back to the original filename. */
  title?: string;
  /** A free-text description of the file */
  description?: string;
}
