/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

export interface UpdateSearchTrendSettingsBodySearchTrendSettings {
  /** Whether search trend recording is enabled */
  trends_enabled?: boolean;
  /** Whether search trends are displayed on the site */
  trends_displayed?: boolean;
  /** The minimum number of searches in the current window for a tag to be rising */
  trends_min_today?: number;
  /** The minimum increase over the previous window for a tag to be rising */
  trends_min_delta?: number;
  /** The minimum ratio between the current and previous window for a tag to be rising */
  trends_min_ratio?: number;
  /** The number of recordings allowed per IP address within the IP window */
  trends_ip_limit?: number;
  /** The IP rate limit window, in seconds */
  trends_ip_window?: number;
  /** The number of recordings allowed per tag within the tag window */
  trends_tag_limit?: number;
  /** The tag rate limit window, in seconds */
  trends_tag_window?: number;
}
