/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */
import type { TicketStatus } from './ticketStatus';

export interface UpdateTicketBody {
  /** The response to the ticket */
  'ticket[response]'?: string;
  'ticket[status]'?: TicketStatus;
  /** The type of record to apply if the ticket content is warnable */
  'ticket[record_type]'?: string;
  /** Whether to send a DMail notification about the update */
  'ticket[send_update_dmail]'?: boolean;
  /** Force claiming the ticket even if already claimed by another user */
  force_claim?: boolean;
}
