/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.

## Authentication

Endpoints with `x-access-level` above `anonymous` require authentication.
Credentials are the account username and an API key issued by `/api_keys.json`,
submitted as either HTTP Basic (username, API key) or the query/body parameters
`login` and `api_key`.

The `x-access-level` extension declares the minimum privilege level for an
operation: `anonymous`, `logged_in`, `member`, `janitor`, `moderator`, `admin`.

 * OpenAPI spec version: dadc1e4c50658851c0205e6ecbfa4723a976b0ab
 */
import type { AppealStatus } from './appealStatus';

export interface UpdateAppealBody {
  /** The response to the appeal */
  'appeal[response]'?: string;
  'appeal[status]'?: AppealStatus;
  /** Whether to send a DMail notification about the update */
  'appeal[send_update_dmail]'?: boolean;
  /** Force claiming the appeal even if already claimed by another user */
  force_claim?: boolean;
}
