/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

export interface UpdateCommentBodyComment {
  /** The comment body text */
  body?: string;
  /** Whether the comment is sticky (janitor only) */
  is_sticky?: boolean;
  /** Whether the comment is hidden (moderator only) */
  is_hidden?: boolean;
}
