/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.

## Authentication

Endpoints with `x-access-level` above `anonymous` require authentication.
Credentials are the account username and an API key issued by `/api_keys.json`,
submitted as either HTTP Basic (username, API key) or the query/body parameters
`login` and `api_key`.

The `x-access-level` extension declares the minimum privilege level for an
operation: `anonymous`, `logged_in`, `member`, `janitor`, `moderator`, `admin`.

 * OpenAPI spec version: dadc1e4c50658851c0205e6ecbfa4723a976b0ab
 */
import type { UpdateForumTopicBodyForumTopicOriginalPostAttributes } from './updateForumTopicBodyForumTopicOriginalPostAttributes';

export interface UpdateForumTopicBodyForumTopic {
  /** The topic title */
  title?: string;
  /** The forum category ID */
  category_id?: number;
  original_post_attributes?: UpdateForumTopicBodyForumTopicOriginalPostAttributes;
  /** Whether the topic is sticky (moderator only) */
  is_sticky?: boolean;
  /** Whether the topic is locked (moderator only) */
  is_locked?: boolean;
}
