/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.

## Authentication

Endpoints with `x-access-level` above `anonymous` require authentication.
Credentials are the account username and an API key issued by `/api_keys.json`,
submitted as either HTTP Basic (username, API key) or the query/body parameters
`login` and `api_key`.

The `x-access-level` extension declares the minimum privilege level for an
operation: `anonymous`, `logged_in`, `member`, `janitor`, `moderator`, `admin`.

 * OpenAPI spec version: dadc1e4c50658851c0205e6ecbfa4723a976b0ab
 */

export interface UpdateUserBodyUser {
  /** Score threshold below which comments are hidden */
  comment_threshold?: number;
  /** Default image display size */
  default_image_size?: string;
  /** User's favorite tags */
  favorite_tags?: string;
  /** Tags to blacklist */
  blacklisted_tags?: string;
  /** User's time zone */
  time_zone?: string;
  /** Number of items per page */
  per_page?: number;
  /** Custom CSS style */
  custom_style?: string;
  /** Whether post descriptions are collapsed by default */
  description_collapsed_initially?: boolean;
  /** Whether to hide comments by default */
  hide_comments?: boolean;
  /** Whether to receive email notifications */
  receive_email_notifications?: boolean;
  /** Whether keyboard navigation is enabled */
  enable_keyboard_navigation?: boolean;
  /** Whether privacy mode is enabled */
  enable_privacy_mode?: boolean;
  /** Whether to disable user DMails */
  disable_user_dmails?: boolean;
  /** Whether to blacklist users */
  blacklist_users?: boolean;
  /** Whether to show post statistics */
  show_post_statistics?: boolean;
  /** Whether to style usernames by level */
  style_usernames?: boolean;
  /** Whether to show hidden comments */
  show_hidden_comments?: boolean;
  /** Whether auto-complete is enabled */
  enable_auto_complete?: boolean;
  /** Whether safe mode is enabled */
  enable_safe_mode?: boolean;
  /** Whether responsive mode is disabled */
  disable_responsive_mode?: boolean;
  /** User's about me text */
  profile_about?: string;
  /** User's artist info text */
  profile_artinfo?: string;
  /** Post ID to use as avatar */
  avatar_id?: number;
  /** New password */
  password?: string;
  /** Current password (required when changing password) */
  old_password?: string;
  /** New password confirmation */
  password_confirmation?: string;
}
