/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

/**
 * Why an upload karma event was recorded
 */
export enum UploadKarmaEventReason {
  approved = 'approved',
  unapproved = 'unapproved',
  deleted = 'deleted',
  undeleted = 'undeleted',
  replacement_penalty = 'replacement_penalty',
  replacement_penalty_reversed = 'replacement_penalty_reversed',
  replacement_transfer = 'replacement_transfer',
  owner_change = 'owner_change',
  staff_override = 'staff_override',
  queue_bypass = 'queue_bypass',
}
