/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.

## Authentication

Endpoints with `x-access-level` above `anonymous` require authentication.
Credentials are the account username and an API key issued by `/api_keys.json`,
submitted as either HTTP Basic (username, API key) or the query/body parameters
`login` and `api_key`.

The `x-access-level` extension declares the minimum privilege level for an
operation: `anonymous`, `logged_in`, `member`, `janitor`, `moderator`, `admin`.

 * OpenAPI spec version: dadc1e4c50658851c0205e6ecbfa4723a976b0ab
 */

/**
 * An upload whitelist entry controlling which domains are allowed for uploads.
 */
export interface UploadWhitelist {
  /** Whether uploads from this domain are allowed */
  allowed: boolean;
  /** When the entry was created */
  created_at: Date;
  /** The domain pattern */
  domain?: string;
  /** Whether the entry is hidden */
  hidden?: boolean;
  /** The unique ID of the whitelist entry */
  id: number;
  /**
   * Note about the whitelist entry
   * @nullable
   */
  note?: string | null;
  /** The path pattern */
  path?: string;
  /**
   * The reason for the entry
   * @nullable
   */
  reason?: string | null;
  /** When the entry was last updated */
  updated_at: Date;
}
