/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

/**
 * Reason-specific detail attached to the event
 */
export type UploadKarmaEventExtraData = { [key: string]: unknown };
