/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */
import type { UserAltUser } from './userAltUser';

/**
 * A suspected alt account, scored on shared-network evidence. Carries no IP or subnet value.
 */
export interface UserAlt {
  /** The ID of the candidate account */
  user_id: number;
  /** Confidence score from 0 to 100, rounded to one decimal place */
  score: number;
  /** Whether a shared IP appears to have been handed over from one account to the other */
  handoff: boolean;
  /**
   * How many distinct accounts were seen on the IP that triggered the handoff, or null when there was no handoff
   * @nullable
   */
  handoff_users: number | null;
  /** Number of exact IP addresses shared with the target */
  shared_exact: number;
  /** Number of subnets shared with the target, excluding those already counted as exact matches */
  shared_subnet: number;
  /** Number of IP addresses recorded for the candidate in the retention window */
  total_ips: number;
  /** Fraction of the candidate's IP addresses that are shared with the target */
  ratio: number;
  /** The smallest number of distinct accounts seen on any of the shared values */
  rarest_users: number;
  /** Earliest activity on a shared value across both accounts */
  overlap_first: Date;
  /** Latest activity on a shared value across both accounts */
  overlap_last: Date;
  /** The most recent time both accounts were still active on the same shared value */
  last_co_seen: Date;
  /** Whether the two accounts' activity windows on a shared value actually overlapped */
  concurrent: boolean;
  /** Whether the candidate account has been anonymized */
  deleted: boolean;
  user: UserAltUser;
}
