/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */
import type { UserFeedbackCategory } from './userFeedbackCategory';

/**
 * A user feedback object representing a piece of feedback left by a user.
 */
export interface UserFeedback {
  /** The unique ID of the user feedback */
  id: number;
  /** The ID of the user who received the feedback */
  user_id: number;
  /** The ID of the user who created the feedback */
  creator_id: number;
  /** The time when the feedback was created */
  created_at: Date;
  /** The body of the feedback, containing the details */
  body: string;
  category: UserFeedbackCategory;
  /** The last time the feedback was updated */
  updated_at: Date;
  /** The ID of the user who last updated the feedback */
  updater_id: number;
  /** Whether the feedback is deleted */
  is_deleted: boolean;
}
