/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.
 * OpenAPI spec version: 1.0.0
 */

/**
 * A simplified representation of a user with core attributes.
 */
export interface User {
  /** The ID of the user's avatar image */
  avatar_id?: number;
  /** The base upload limit for the user */
  base_upload_limit: number;
  /** Whether the user can approve posts */
  can_approve_posts: boolean;
  /** Whether the user can upload without restrictions */
  can_upload_free: boolean;
  /** The timestamp when the user account was created */
  created_at: Date;
  /** The unique ID of the user */
  id: number;
  /** Whether the user is banned */
  is_banned: boolean;
  /** The user's access level (numerical) */
  level: number;
  /** The user's access level (textual description) */
  level_string: string;
  /** The username of the user */
  name: string;
  /** Number of note updates made by the user */
  note_update_count: number;
  /** Number of post updates made by the user */
  post_update_count: number;
  /** Number of posts uploaded by the user */
  post_upload_count: number;
}
