/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

/**
 * A detailed representation of a user.
 */
export interface UserProfile {
  /** Number of wiki page versions created by the user */
  wiki_page_version_count?: number;
  /** Number of artist versions created by the user */
  artist_version_count?: number;
  /** Number of pool versions created by the user */
  pool_version_count?: number;
  /** Number of forum posts created by the user */
  forum_post_count?: number;
  /** Number of comments made by the user */
  comment_count?: number;
  /** Number of flags made by the user */
  flag_count?: number;
  /** Number of favorites added by the user */
  favorite_count?: number;
  /** Number of positive feedbacks received by the user */
  positive_feedback_count?: number;
  /** Number of neutral feedbacks received by the user */
  neutral_feedback_count?: number;
  /** Number of negative feedbacks received by the user */
  negative_feedback_count?: number;
  /** The number of upload slots available to the user */
  upload_slots?: number;
  /** The user's "About" profile section */
  profile_about?: string;
  /** The user's art information profile section */
  profile_artinfo?: string;
  /** The unique ID of the user */
  id: number;
  /** The timestamp when the user account was created */
  created_at: Date;
  /** The username of the user */
  name: string;
  /** The user's access level (numerical) */
  level: number;
  /** The base upload limit for the user */
  base_upload_limit: number;
  /** The user's upload karma */
  upload_karma: number;
  /** Whether the user is exempt from the upload karma system */
  upload_karma_free: boolean;
  /** Number of posts uploaded by the user */
  post_upload_count: number;
  /** Number of post updates made by the user */
  post_update_count: number;
  /** Number of note updates made by the user */
  note_update_count: number;
  /** Whether the user is banned */
  is_banned: boolean;
  /** Whether the user can approve posts */
  can_approve_posts: boolean;
  /** Whether the user can upload without restrictions */
  can_upload_free: boolean;
  /** The user's access level (textual description) */
  level_string: string;
  /** The ID of the user's avatar image */
  avatar_id?: number;
  /** Whether the user has verified their email */
  is_verified?: boolean;
  /** Whether the user has a server-side cropped avatar */
  has_cropped_avatar?: boolean;
}
