/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

/**
 * The identifying fields of a suspected alt account.
 */
export interface UserAltUser {
  /** The unique ID of the user */
  id: number;
  /** The username of the user */
  name: string;
  /** The user's access level (textual description) */
  level_string: string;
  /** The timestamp when the user account was created */
  created_at: Date;
}
