/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.

## Authentication

Endpoints with `x-access-level` above `anonymous` require authentication.
Credentials are the account username and an API key issued by `/api_keys.json`,
submitted as either HTTP Basic (username, API key) or the query/body parameters
`login` and `api_key`.

The `x-access-level` extension declares the minimum privilege level for an
operation: `anonymous`, `logged_in`, `member`, `janitor`, `moderator`, `admin`.

 * OpenAPI spec version: dadc1e4c50658851c0205e6ecbfa4723a976b0ab
 */

/**
 * A request to change a user's name.
 */
export interface UserNameChangeRequest {
  /** The unique ID of the name change request */
  id: number;
  /** The status of the request */
  status?: string;
  /** The ID of the user requesting the change */
  user_id: number;
  /**
   * The ID of the approving moderator
   * @nullable
   */
  approver_id?: number | null;
  /** The user's original name */
  original_name: string;
  /** The requested new name */
  desired_name: string;
  /**
   * The reason for the name change
   * @nullable
   */
  change_reason?: string | null;
  /**
   * The reason for rejecting the request
   * @nullable
   */
  rejection_reason?: string | null;
  /** When the request was created */
  created_at: Date;
  /** When the request was last updated */
  updated_at: Date;
}
