/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

/**
 * Which of the current user's content listings are non-empty.
 */
export interface UserAvatarMenu {
  /** Whether the user has uploaded any posts */
  has_uploads: boolean;
  /** Whether the user has any favorites */
  has_favorites: boolean;
  /** Whether the user owns any post sets */
  has_sets: boolean;
  /** Whether the user has posted any comments */
  has_comments: boolean;
  /** Whether the user has posted in the forums */
  has_forums: boolean;
  /** Whether the user has posted any blips */
  has_blips: boolean;
}
