/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.

## Authentication

Endpoints with `x-access-level` above `anonymous` require authentication.
Credentials are the account username and an API key issued by `/api_keys.json`,
submitted as either HTTP Basic (username, API key) or the query/body parameters
`login` and `api_key`.

The `x-access-level` extension declares the minimum privilege level for an
operation: `anonymous`, `logged_in`, `member`, `janitor`, `moderator`, `admin`.

 * OpenAPI spec version: dadc1e4c50658851c0205e6ecbfa4723a976b0ab
 */

export interface WikiPage {
  /** The body content of the wiki page */
  body: string;
  /**
   * The tag category ID associated with the wiki page
   * @nullable
   */
  category_id?: number | null;
  /** When the wiki page was created */
  created_at: Date;
  /** The ID of the user who created the wiki page */
  creator_id: number;
  /** The username of the creator */
  creator_name?: string;
  /** The unique ID of the wiki page */
  id: number;
  /** Whether the wiki page is deleted */
  is_deleted: boolean;
  /** Whether the wiki page is locked */
  is_locked: boolean;
  /** Alternative names for the wiki page */
  other_names: string[];
  /**
   * The parent wiki page title for redirects
   * @nullable
   */
  parent?: string | null;
  /** The title of the wiki page */
  title: string;
  /** When the wiki page was last updated */
  updated_at: Date;
  /**
   * The ID of the user who last updated the wiki page
   * @nullable
   */
  updater_id?: number | null;
}
