/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

export interface WikiPageVersion {
  /** The unique ID of the wiki page version */
  id: number;
  /** The ID of the wiki page */
  wiki_page_id: number;
  /** The ID of the user who made this version */
  updater_id: number;
  /** The title at this version */
  title: string;
  /** The body content at this version */
  body: string;
  /** Whether the page was locked at this version */
  is_locked: boolean;
  /** Whether the page was deleted at this version */
  is_deleted: boolean;
  /** Alternative names at this version */
  other_names: string[];
  /** The IDs of the posts featured on the page at this version */
  featured_posts: number[];
  /**
   * The edit reason for this version
   * @nullable
   */
  reason?: string | null;
  /**
   * The parent wiki page title at this version
   * @nullable
   */
  parent?: string | null;
  /** When this version was created */
  created_at: Date;
  /** When this version was last updated */
  updated_at: Date;
}
