/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.
 * OpenAPI spec version: 1.0.0
 */
import type {
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { useInfiniteQuery, useQuery } from "@tanstack/react-query";

import type { ErrorType } from "../http/axios";
import { makeRequest } from "../http/axios";
import type { GetUploadsParams, Upload } from "./model";

/**
 * Returns a list of uploads based on search criteria.
 * @summary Get a list of uploads
 */
export const uploads = (params?: GetUploadsParams, signal?: AbortSignal) => {
  return makeRequest<Upload[]>({
    url: `/uploads.json`,
    method: "GET",
    params,
    signal,
  });
};

export const getUploadsQueryKey = (params?: GetUploadsParams) => {
  return [`/uploads.json`, ...(params ? [params] : [])] as const;
};

export const getUploadsInfiniteQueryOptions = <
  TData = InfiniteData<
    Awaited<ReturnType<typeof uploads>>,
    GetUploadsParams["page"]
  >,
  TError = ErrorType<void>,
>(
  params?: GetUploadsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof uploads>>,
        TError,
        TData,
        Awaited<ReturnType<typeof uploads>>,
        QueryKey,
        GetUploadsParams["page"]
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUploadsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof uploads>>,
    QueryKey,
    GetUploadsParams["page"]
  > = ({ signal, pageParam }) =>
    uploads({ ...params, page: pageParam || params?.["page"] }, signal);

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof uploads>>,
    TError,
    TData,
    Awaited<ReturnType<typeof uploads>>,
    QueryKey,
    GetUploadsParams["page"]
  > & { queryKey: QueryKey };
};

export type UploadsInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof uploads>>
>;
export type UploadsInfiniteQueryError = ErrorType<void>;

export function useUploadsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof uploads>>,
    GetUploadsParams["page"]
  >,
  TError = ErrorType<void>,
>(
  params: undefined | GetUploadsParams,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof uploads>>,
        TError,
        TData,
        Awaited<ReturnType<typeof uploads>>,
        QueryKey,
        GetUploadsParams["page"]
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof uploads>>,
          TError,
          TData,
          QueryKey
        >,
        "initialData"
      >;
  },
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey };
export function useUploadsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof uploads>>,
    GetUploadsParams["page"]
  >,
  TError = ErrorType<void>,
>(
  params?: GetUploadsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof uploads>>,
        TError,
        TData,
        Awaited<ReturnType<typeof uploads>>,
        QueryKey,
        GetUploadsParams["page"]
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof uploads>>,
          TError,
          TData,
          QueryKey
        >,
        "initialData"
      >;
  },
): UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey };
export function useUploadsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof uploads>>,
    GetUploadsParams["page"]
  >,
  TError = ErrorType<void>,
>(
  params?: GetUploadsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof uploads>>,
        TError,
        TData,
        Awaited<ReturnType<typeof uploads>>,
        QueryKey,
        GetUploadsParams["page"]
      >
    >;
  },
): UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey };
/**
 * @summary Get a list of uploads
 */

export function useUploadsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof uploads>>,
    GetUploadsParams["page"]
  >,
  TError = ErrorType<void>,
>(
  params?: GetUploadsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof uploads>>,
        TError,
        TData,
        Awaited<ReturnType<typeof uploads>>,
        QueryKey,
        GetUploadsParams["page"]
      >
    >;
  },
): UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getUploadsInfiniteQueryOptions(params, options);

  const query = useInfiniteQuery(queryOptions) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getUploadsQueryOptions = <
  TData = Awaited<ReturnType<typeof uploads>>,
  TError = ErrorType<void>,
>(
  params?: GetUploadsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof uploads>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUploadsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof uploads>>> = ({
    signal,
  }) => uploads(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof uploads>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type UploadsQueryResult = NonNullable<
  Awaited<ReturnType<typeof uploads>>
>;
export type UploadsQueryError = ErrorType<void>;

export function useUploads<
  TData = Awaited<ReturnType<typeof uploads>>,
  TError = ErrorType<void>,
>(
  params: undefined | GetUploadsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof uploads>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof uploads>>,
          TError,
          TData
        >,
        "initialData"
      >;
  },
): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useUploads<
  TData = Awaited<ReturnType<typeof uploads>>,
  TError = ErrorType<void>,
>(
  params?: GetUploadsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof uploads>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof uploads>>,
          TError,
          TData
        >,
        "initialData"
      >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useUploads<
  TData = Awaited<ReturnType<typeof uploads>>,
  TError = ErrorType<void>,
>(
  params?: GetUploadsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof uploads>>, TError, TData>
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey };
/**
 * @summary Get a list of uploads
 */

export function useUploads<
  TData = Awaited<ReturnType<typeof uploads>>,
  TError = ErrorType<void>,
>(
  params?: GetUploadsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof uploads>>, TError, TData>
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getUploadsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Returns detailed information about a specific upload identified by its ID.
 * @summary Get an upload by ID
 */
export const upload = (id: number, signal?: AbortSignal) => {
  return makeRequest<Upload>({
    url: `/uploads/${encodeURIComponent(String(id))}.json`,
    method: "GET",
    signal,
  });
};

export const getUploadQueryKey = (id: number) => {
  return [`/uploads/${id}.json`] as const;
};

export const getUploadQueryOptions = <
  TData = Awaited<ReturnType<typeof upload>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof upload>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUploadQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof upload>>> = ({
    signal,
  }) => upload(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof upload>>, TError, TData> & {
    queryKey: QueryKey;
  };
};

export type UploadQueryResult = NonNullable<Awaited<ReturnType<typeof upload>>>;
export type UploadQueryError = ErrorType<void>;

export function useUpload<
  TData = Awaited<ReturnType<typeof upload>>,
  TError = ErrorType<void>,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof upload>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof upload>>,
          TError,
          TData
        >,
        "initialData"
      >;
  },
): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useUpload<
  TData = Awaited<ReturnType<typeof upload>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof upload>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof upload>>,
          TError,
          TData
        >,
        "initialData"
      >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useUpload<
  TData = Awaited<ReturnType<typeof upload>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof upload>>, TError, TData>
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey };
/**
 * @summary Get an upload by ID
 */

export function useUpload<
  TData = Awaited<ReturnType<typeof upload>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof upload>>, TError, TData>
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getUploadQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
