/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * @6oclock/api
 * backend data aggregate for 6 o'clock
 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetJobsParams,
  JobInfo,
  SchedulerInfo
} from './model';

import { makeRequest } from '../http/axios';
import type { ErrorType } from '../http/axios';





/**
 * Returns a list of all jobs that have been queued or processed.
 * @summary Get all jobs
 */
export const jobs = (
    params?: GetJobsParams,
 signal?: AbortSignal
) => {
      
      
      return makeRequest<JobInfo[]>(
      {url: `/api/jobs`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getJobsInfiniteQueryKey = (params?: GetJobsParams,) => {
    return [
    'infinite', `/api/jobs`, ...(params ? [params]: [])
    ] as const;
    }

export const getJobsQueryKey = (params?: GetJobsParams,) => {
    return [
    `/api/jobs`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getJobsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof jobs>>, GetJobsParams['page']>, TError = ErrorType<unknown>>(params?: GetJobsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof jobs>>, TError, TData, QueryKey, GetJobsParams['page']>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getJobsInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof jobs>>, QueryKey, GetJobsParams['page']> = ({ signal, pageParam }) => jobs({...params, 'page': pageParam || params?.['page']}, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof jobs>>, TError, TData, QueryKey, GetJobsParams['page']> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type JobsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof jobs>>>
export type JobsInfiniteQueryError = ErrorType<unknown>


export function useJobsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof jobs>>, GetJobsParams['page']>, TError = ErrorType<unknown>>(
 params: undefined |  GetJobsParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof jobs>>, TError, TData, QueryKey, GetJobsParams['page']>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof jobs>>,
          TError,
          Awaited<ReturnType<typeof jobs>>, QueryKey
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useJobsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof jobs>>, GetJobsParams['page']>, TError = ErrorType<unknown>>(
 params?: GetJobsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof jobs>>, TError, TData, QueryKey, GetJobsParams['page']>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof jobs>>,
          TError,
          Awaited<ReturnType<typeof jobs>>, QueryKey
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useJobsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof jobs>>, GetJobsParams['page']>, TError = ErrorType<unknown>>(
 params?: GetJobsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof jobs>>, TError, TData, QueryKey, GetJobsParams['page']>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all jobs
 */

export function useJobsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof jobs>>, GetJobsParams['page']>, TError = ErrorType<unknown>>(
 params?: GetJobsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof jobs>>, TError, TData, QueryKey, GetJobsParams['page']>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getJobsInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getJobsQueryOptions = <TData = Awaited<ReturnType<typeof jobs>>, TError = ErrorType<unknown>>(params?: GetJobsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof jobs>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getJobsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof jobs>>> = ({ signal }) => jobs(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof jobs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type JobsQueryResult = NonNullable<Awaited<ReturnType<typeof jobs>>>
export type JobsQueryError = ErrorType<unknown>


export function useJobs<TData = Awaited<ReturnType<typeof jobs>>, TError = ErrorType<unknown>>(
 params: undefined |  GetJobsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof jobs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof jobs>>,
          TError,
          Awaited<ReturnType<typeof jobs>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useJobs<TData = Awaited<ReturnType<typeof jobs>>, TError = ErrorType<unknown>>(
 params?: GetJobsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof jobs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof jobs>>,
          TError,
          Awaited<ReturnType<typeof jobs>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useJobs<TData = Awaited<ReturnType<typeof jobs>>, TError = ErrorType<unknown>>(
 params?: GetJobsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof jobs>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all jobs
 */

export function useJobs<TData = Awaited<ReturnType<typeof jobs>>, TError = ErrorType<unknown>>(
 params?: GetJobsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof jobs>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getJobsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Returns a list of all registered job schedulers.
 * @summary Get all job schedulers
 */
export const jobSchedulers = (
    
 signal?: AbortSignal
) => {
      
      
      return makeRequest<SchedulerInfo[]>(
      {url: `/api/jobs/schedulers`, method: 'GET', signal
    },
      );
    }
  



export const getJobSchedulersQueryKey = () => {
    return [
    `/api/jobs/schedulers`
    ] as const;
    }

    
export const getJobSchedulersQueryOptions = <TData = Awaited<ReturnType<typeof jobSchedulers>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof jobSchedulers>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getJobSchedulersQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof jobSchedulers>>> = ({ signal }) => jobSchedulers(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof jobSchedulers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type JobSchedulersQueryResult = NonNullable<Awaited<ReturnType<typeof jobSchedulers>>>
export type JobSchedulersQueryError = ErrorType<unknown>


export function useJobSchedulers<TData = Awaited<ReturnType<typeof jobSchedulers>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof jobSchedulers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof jobSchedulers>>,
          TError,
          Awaited<ReturnType<typeof jobSchedulers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useJobSchedulers<TData = Awaited<ReturnType<typeof jobSchedulers>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof jobSchedulers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof jobSchedulers>>,
          TError,
          Awaited<ReturnType<typeof jobSchedulers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useJobSchedulers<TData = Awaited<ReturnType<typeof jobSchedulers>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof jobSchedulers>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all job schedulers
 */

export function useJobSchedulers<TData = Awaited<ReturnType<typeof jobSchedulers>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof jobSchedulers>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getJobSchedulersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Enables a previously disabled job scheduler.
 * @summary Enable a job scheduler
 */
export const enableJobScheduler = (
    id: string,
 ) => {
      
      
      return makeRequest<void>(
      {url: `/api/jobs/schedulers/${encodeURIComponent(String(id))}/enable`, method: 'PUT'
    },
      );
    }
  


export const getEnableJobSchedulerMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof enableJobScheduler>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof enableJobScheduler>>, TError,{id: string}, TContext> => {

const mutationKey = ['enableJobScheduler'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof enableJobScheduler>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  enableJobScheduler(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type EnableJobSchedulerMutationResult = NonNullable<Awaited<ReturnType<typeof enableJobScheduler>>>
    
    export type EnableJobSchedulerMutationError = ErrorType<unknown>

    /**
 * @summary Enable a job scheduler
 */
export const useEnableJobScheduler = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof enableJobScheduler>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof enableJobScheduler>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getEnableJobSchedulerMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Disables a job scheduler, preventing it from creating jobs.
 * @summary Disable a job scheduler
 */
export const disableJobScheduler = (
    id: string,
 ) => {
      
      
      return makeRequest<void>(
      {url: `/api/jobs/schedulers/${encodeURIComponent(String(id))}/disable`, method: 'PUT'
    },
      );
    }
  


export const getDisableJobSchedulerMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof disableJobScheduler>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof disableJobScheduler>>, TError,{id: string}, TContext> => {

const mutationKey = ['disableJobScheduler'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof disableJobScheduler>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  disableJobScheduler(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DisableJobSchedulerMutationResult = NonNullable<Awaited<ReturnType<typeof disableJobScheduler>>>
    
    export type DisableJobSchedulerMutationError = ErrorType<unknown>

    /**
 * @summary Disable a job scheduler
 */
export const useDisableJobScheduler = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof disableJobScheduler>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof disableJobScheduler>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDisableJobSchedulerMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    