/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * @6oclock/api
 * backend data aggregate for 6 o'clock
 * OpenAPI spec version: 1.0.0
 */
import { useInfiniteQuery, useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { makeRequest } from '../http/axios';
import type { ErrorType } from '../http/axios';
import type {
  GetJobLogsParams,
  GetJobsParams,
  JobInfo,
  JobLogInfo,
  JobOverview,
  SchedulerInfo,
  SchedulerState,
} from './model';

/**
 * Returns a list of all jobs that have been queued or processed, optionally limited to one scheduler.
 * @summary Get all jobs
 */
export const jobs = (params?: GetJobsParams, signal?: AbortSignal) => {
  return makeRequest<JobInfo[]>({
    url: `/jobs`,
    method: 'GET',
    params,
    signal,
  });
};

export const getJobsInfiniteQueryKey = (params?: GetJobsParams) => {
  return ['infinite', `/jobs`, ...(params ? [params] : [])] as const;
};

export const getJobsQueryKey = (params?: GetJobsParams) => {
  return [`/jobs`, ...(params ? [params] : [])] as const;
};

export const getJobsInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof jobs>>, GetJobsParams['page']>,
  TError = ErrorType<unknown>,
>(
  params?: GetJobsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof jobs>>,
        TError,
        TData,
        QueryKey,
        GetJobsParams['page']
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getJobsInfiniteQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof jobs>>,
    QueryKey,
    GetJobsParams['page']
  > = ({ signal, pageParam }) =>
    jobs({ ...params, page: pageParam || params?.['page'] }, signal);

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof jobs>>,
    TError,
    TData,
    QueryKey,
    GetJobsParams['page']
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type JobsInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof jobs>>
>;
export type JobsInfiniteQueryError = ErrorType<unknown>;

export function useJobsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof jobs>>, GetJobsParams['page']>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetJobsParams,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof jobs>>,
        TError,
        TData,
        QueryKey,
        GetJobsParams['page']
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof jobs>>,
          TError,
          Awaited<ReturnType<typeof jobs>>,
          QueryKey
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useJobsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof jobs>>, GetJobsParams['page']>,
  TError = ErrorType<unknown>,
>(
  params?: GetJobsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof jobs>>,
        TError,
        TData,
        QueryKey,
        GetJobsParams['page']
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof jobs>>,
          TError,
          Awaited<ReturnType<typeof jobs>>,
          QueryKey
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useJobsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof jobs>>, GetJobsParams['page']>,
  TError = ErrorType<unknown>,
>(
  params?: GetJobsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof jobs>>,
        TError,
        TData,
        QueryKey,
        GetJobsParams['page']
      >
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get all jobs
 */

export function useJobsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof jobs>>, GetJobsParams['page']>,
  TError = ErrorType<unknown>,
>(
  params?: GetJobsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof jobs>>,
        TError,
        TData,
        QueryKey,
        GetJobsParams['page']
      >
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getJobsInfiniteQueryOptions(params, options);

  const query = useInfiniteQuery(
    queryOptions,
    queryClient,
  ) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getJobsQueryOptions = <
  TData = Awaited<ReturnType<typeof jobs>>,
  TError = ErrorType<unknown>,
>(
  params?: GetJobsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof jobs>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getJobsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof jobs>>> = ({
    signal,
  }) => jobs(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof jobs>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type JobsQueryResult = NonNullable<Awaited<ReturnType<typeof jobs>>>;
export type JobsQueryError = ErrorType<unknown>;

export function useJobs<
  TData = Awaited<ReturnType<typeof jobs>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetJobsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof jobs>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof jobs>>,
          TError,
          Awaited<ReturnType<typeof jobs>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useJobs<
  TData = Awaited<ReturnType<typeof jobs>>,
  TError = ErrorType<unknown>,
>(
  params?: GetJobsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof jobs>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof jobs>>,
          TError,
          Awaited<ReturnType<typeof jobs>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useJobs<
  TData = Awaited<ReturnType<typeof jobs>>,
  TError = ErrorType<unknown>,
>(
  params?: GetJobsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof jobs>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get all jobs
 */

export function useJobs<
  TData = Awaited<ReturnType<typeof jobs>>,
  TError = ErrorType<unknown>,
>(
  params?: GetJobsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof jobs>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getJobsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Returns every registered scheduler beside the outcome of its most recent job.
 * @summary Get one row per scheduler with its last run
 */
export const jobOverview = (signal?: AbortSignal) => {
  return makeRequest<JobOverview[]>({
    url: `/jobs/overview`,
    method: 'GET',
    signal,
  });
};

export const getJobOverviewQueryKey = () => {
  return [`/jobs/overview`] as const;
};

export const getJobOverviewQueryOptions = <
  TData = Awaited<ReturnType<typeof jobOverview>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof jobOverview>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getJobOverviewQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof jobOverview>>> = ({
    signal,
  }) => jobOverview(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof jobOverview>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type JobOverviewQueryResult = NonNullable<
  Awaited<ReturnType<typeof jobOverview>>
>;
export type JobOverviewQueryError = ErrorType<unknown>;

export function useJobOverview<
  TData = Awaited<ReturnType<typeof jobOverview>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof jobOverview>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof jobOverview>>,
          TError,
          Awaited<ReturnType<typeof jobOverview>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useJobOverview<
  TData = Awaited<ReturnType<typeof jobOverview>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof jobOverview>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof jobOverview>>,
          TError,
          Awaited<ReturnType<typeof jobOverview>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useJobOverview<
  TData = Awaited<ReturnType<typeof jobOverview>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof jobOverview>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get one row per scheduler with its last run
 */

export function useJobOverview<
  TData = Awaited<ReturnType<typeof jobOverview>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof jobOverview>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getJobOverviewQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Returns the lines a single run wrote while it held a turn.
 * @summary Get the log of one run
 */
export const jobLogs = (
  id: string,
  params?: GetJobLogsParams,
  signal?: AbortSignal,
) => {
  return makeRequest<JobLogInfo[]>({
    url: `/jobs/${encodeURIComponent(String(id))}/logs`,
    method: 'GET',
    params,
    signal,
  });
};

export const getJobLogsInfiniteQueryKey = (
  id?: string,
  params?: GetJobLogsParams,
) => {
  return ['infinite', `/jobs/${id}/logs`, ...(params ? [params] : [])] as const;
};

export const getJobLogsQueryKey = (id?: string, params?: GetJobLogsParams) => {
  return [`/jobs/${id}/logs`, ...(params ? [params] : [])] as const;
};

export const getJobLogsInfiniteQueryOptions = <
  TData = InfiniteData<
    Awaited<ReturnType<typeof jobLogs>>,
    GetJobLogsParams['before']
  >,
  TError = ErrorType<unknown>,
>(
  id: string,
  params?: GetJobLogsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof jobLogs>>,
        TError,
        TData,
        QueryKey,
        GetJobLogsParams['before']
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getJobLogsInfiniteQueryKey(id, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof jobLogs>>,
    QueryKey,
    GetJobLogsParams['before']
  > = ({ signal, pageParam }) =>
    jobLogs(id, { ...params, before: pageParam || params?.['before'] }, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof jobLogs>>,
    TError,
    TData,
    QueryKey,
    GetJobLogsParams['before']
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type JobLogsInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof jobLogs>>
>;
export type JobLogsInfiniteQueryError = ErrorType<unknown>;

export function useJobLogsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof jobLogs>>,
    GetJobLogsParams['before']
  >,
  TError = ErrorType<unknown>,
>(
  id: string,
  params: undefined | GetJobLogsParams,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof jobLogs>>,
        TError,
        TData,
        QueryKey,
        GetJobLogsParams['before']
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof jobLogs>>,
          TError,
          Awaited<ReturnType<typeof jobLogs>>,
          QueryKey
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useJobLogsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof jobLogs>>,
    GetJobLogsParams['before']
  >,
  TError = ErrorType<unknown>,
>(
  id: string,
  params?: GetJobLogsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof jobLogs>>,
        TError,
        TData,
        QueryKey,
        GetJobLogsParams['before']
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof jobLogs>>,
          TError,
          Awaited<ReturnType<typeof jobLogs>>,
          QueryKey
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useJobLogsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof jobLogs>>,
    GetJobLogsParams['before']
  >,
  TError = ErrorType<unknown>,
>(
  id: string,
  params?: GetJobLogsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof jobLogs>>,
        TError,
        TData,
        QueryKey,
        GetJobLogsParams['before']
      >
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get the log of one run
 */

export function useJobLogsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof jobLogs>>,
    GetJobLogsParams['before']
  >,
  TError = ErrorType<unknown>,
>(
  id: string,
  params?: GetJobLogsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof jobLogs>>,
        TError,
        TData,
        QueryKey,
        GetJobLogsParams['before']
      >
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getJobLogsInfiniteQueryOptions(id, params, options);

  const query = useInfiniteQuery(
    queryOptions,
    queryClient,
  ) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getJobLogsQueryOptions = <
  TData = Awaited<ReturnType<typeof jobLogs>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  params?: GetJobLogsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof jobLogs>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getJobLogsQueryKey(id, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof jobLogs>>> = ({
    signal,
  }) => jobLogs(id, params, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof jobLogs>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type JobLogsQueryResult = NonNullable<
  Awaited<ReturnType<typeof jobLogs>>
>;
export type JobLogsQueryError = ErrorType<unknown>;

export function useJobLogs<
  TData = Awaited<ReturnType<typeof jobLogs>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  params: undefined | GetJobLogsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof jobLogs>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof jobLogs>>,
          TError,
          Awaited<ReturnType<typeof jobLogs>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useJobLogs<
  TData = Awaited<ReturnType<typeof jobLogs>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  params?: GetJobLogsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof jobLogs>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof jobLogs>>,
          TError,
          Awaited<ReturnType<typeof jobLogs>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useJobLogs<
  TData = Awaited<ReturnType<typeof jobLogs>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  params?: GetJobLogsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof jobLogs>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get the log of one run
 */

export function useJobLogs<
  TData = Awaited<ReturnType<typeof jobLogs>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  params?: GetJobLogsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof jobLogs>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getJobLogsQueryOptions(id, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Returns a list of all registered job schedulers.
 * @summary Get all job schedulers
 */
export const jobSchedulers = (signal?: AbortSignal) => {
  return makeRequest<SchedulerInfo[]>({
    url: `/jobs/schedulers`,
    method: 'GET',
    signal,
  });
};

export const getJobSchedulersQueryKey = () => {
  return [`/jobs/schedulers`] as const;
};

export const getJobSchedulersQueryOptions = <
  TData = Awaited<ReturnType<typeof jobSchedulers>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof jobSchedulers>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getJobSchedulersQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof jobSchedulers>>> = ({
    signal,
  }) => jobSchedulers(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof jobSchedulers>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type JobSchedulersQueryResult = NonNullable<
  Awaited<ReturnType<typeof jobSchedulers>>
>;
export type JobSchedulersQueryError = ErrorType<unknown>;

export function useJobSchedulers<
  TData = Awaited<ReturnType<typeof jobSchedulers>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof jobSchedulers>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof jobSchedulers>>,
          TError,
          Awaited<ReturnType<typeof jobSchedulers>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useJobSchedulers<
  TData = Awaited<ReturnType<typeof jobSchedulers>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof jobSchedulers>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof jobSchedulers>>,
          TError,
          Awaited<ReturnType<typeof jobSchedulers>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useJobSchedulers<
  TData = Awaited<ReturnType<typeof jobSchedulers>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof jobSchedulers>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get all job schedulers
 */

export function useJobSchedulers<
  TData = Awaited<ReturnType<typeof jobSchedulers>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof jobSchedulers>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getJobSchedulersQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Schedules a handler on its queue, or unschedules it so it creates no further jobs. Handler ids carry a slash, so the id travels in the body.
 * @summary Enable or disable a job scheduler
 */
export const setJobScheduler = (schedulerState: SchedulerState) => {
  return makeRequest<void>({
    url: `/jobs/schedulers`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: schedulerState,
  });
};

export const getSetJobSchedulerMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof setJobScheduler>>,
    TError,
    { data: SchedulerState },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof setJobScheduler>>,
  TError,
  { data: SchedulerState },
  TContext
> => {
  const mutationKey = ['setJobScheduler'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof setJobScheduler>>,
    { data: SchedulerState }
  > = (props) => {
    const { data } = props ?? {};

    return setJobScheduler(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type SetJobSchedulerMutationResult = NonNullable<
  Awaited<ReturnType<typeof setJobScheduler>>
>;
export type SetJobSchedulerMutationBody = SchedulerState;
export type SetJobSchedulerMutationError = ErrorType<unknown>;

/**
 * @summary Enable or disable a job scheduler
 */
export const useSetJobScheduler = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof setJobScheduler>>,
      TError,
      { data: SchedulerState },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof setJobScheduler>>,
  TError,
  { data: SchedulerState },
  TContext
> => {
  const mutationOptions = getSetJobSchedulerMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
