/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * 5-thirty
 * backend data aggregate for 6 o'clock
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { makeRequest } from '../http/axios';
import type { ErrorType } from '../http/axios';





/**
 * Proxies a request to the static host and returns the file as a stream
 * @summary Proxy request to static host
 */
export const proxyRequest = (
    
 signal?: AbortSignal
) => {
      
      
      return makeRequest<void>(
      {url: `/proxy/*`, method: 'GET', signal
    },
      );
    }
  

export const getProxyRequestQueryKey = () => {
    return [`/proxy/*`] as const;
    }

    
export const getProxyRequestQueryOptions = <TData = Awaited<ReturnType<typeof proxyRequest>>, TError = ErrorType<void>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof proxyRequest>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProxyRequestQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof proxyRequest>>> = ({ signal }) => proxyRequest(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof proxyRequest>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProxyRequestQueryResult = NonNullable<Awaited<ReturnType<typeof proxyRequest>>>
export type ProxyRequestQueryError = ErrorType<void>


export function useProxyRequest<TData = Awaited<ReturnType<typeof proxyRequest>>, TError = ErrorType<void>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof proxyRequest>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof proxyRequest>>,
          TError,
          Awaited<ReturnType<typeof proxyRequest>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProxyRequest<TData = Awaited<ReturnType<typeof proxyRequest>>, TError = ErrorType<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof proxyRequest>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof proxyRequest>>,
          TError,
          Awaited<ReturnType<typeof proxyRequest>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProxyRequest<TData = Awaited<ReturnType<typeof proxyRequest>>, TError = ErrorType<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof proxyRequest>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Proxy request to static host
 */

export function useProxyRequest<TData = Awaited<ReturnType<typeof proxyRequest>>, TError = ErrorType<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof proxyRequest>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProxyRequestQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



