/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.
 * OpenAPI spec version: 1.0.0
 */
import { useInfiniteQuery, useQuery } from "@tanstack/react-query";
import type {
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type { GetUserFeedbacksParams, UserFeedback } from "./model";
import { makeRequest } from "../http/axios";
import type { ErrorType } from "../http/axios";

/**
 * Returns a list of user feedbacks based on search criteria.
 * @summary Get a list of user feedbacks
 */
export const userFeedbacks = (
  params?: GetUserFeedbacksParams,
  signal?: AbortSignal,
) => {
  return makeRequest<UserFeedback[]>({
    url: `/user_feedbacks.json`,
    method: "GET",
    params,
    signal,
  });
};

export const getUserFeedbacksQueryKey = (params?: GetUserFeedbacksParams) => {
  return [`/user_feedbacks.json`, ...(params ? [params] : [])] as const;
};

export const getUserFeedbacksInfiniteQueryOptions = <
  TData = InfiniteData<
    Awaited<ReturnType<typeof userFeedbacks>>,
    GetUserFeedbacksParams["page"]
  >,
  TError = ErrorType<void>,
>(
  params?: GetUserFeedbacksParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof userFeedbacks>>,
        TError,
        TData,
        Awaited<ReturnType<typeof userFeedbacks>>,
        QueryKey,
        GetUserFeedbacksParams["page"]
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUserFeedbacksQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof userFeedbacks>>,
    QueryKey,
    GetUserFeedbacksParams["page"]
  > = ({ signal, pageParam }) =>
    userFeedbacks({ ...params, page: pageParam || params?.["page"] }, signal);

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof userFeedbacks>>,
    TError,
    TData,
    Awaited<ReturnType<typeof userFeedbacks>>,
    QueryKey,
    GetUserFeedbacksParams["page"]
  > & { queryKey: QueryKey };
};

export type UserFeedbacksInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof userFeedbacks>>
>;
export type UserFeedbacksInfiniteQueryError = ErrorType<void>;

export function useUserFeedbacksInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof userFeedbacks>>,
    GetUserFeedbacksParams["page"]
  >,
  TError = ErrorType<void>,
>(
  params: undefined | GetUserFeedbacksParams,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof userFeedbacks>>,
        TError,
        TData,
        Awaited<ReturnType<typeof userFeedbacks>>,
        QueryKey,
        GetUserFeedbacksParams["page"]
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof userFeedbacks>>,
          TError,
          TData,
          QueryKey
        >,
        "initialData"
      >;
  },
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey };
export function useUserFeedbacksInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof userFeedbacks>>,
    GetUserFeedbacksParams["page"]
  >,
  TError = ErrorType<void>,
>(
  params?: GetUserFeedbacksParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof userFeedbacks>>,
        TError,
        TData,
        Awaited<ReturnType<typeof userFeedbacks>>,
        QueryKey,
        GetUserFeedbacksParams["page"]
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof userFeedbacks>>,
          TError,
          TData,
          QueryKey
        >,
        "initialData"
      >;
  },
): UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey };
export function useUserFeedbacksInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof userFeedbacks>>,
    GetUserFeedbacksParams["page"]
  >,
  TError = ErrorType<void>,
>(
  params?: GetUserFeedbacksParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof userFeedbacks>>,
        TError,
        TData,
        Awaited<ReturnType<typeof userFeedbacks>>,
        QueryKey,
        GetUserFeedbacksParams["page"]
      >
    >;
  },
): UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey };
/**
 * @summary Get a list of user feedbacks
 */

export function useUserFeedbacksInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof userFeedbacks>>,
    GetUserFeedbacksParams["page"]
  >,
  TError = ErrorType<void>,
>(
  params?: GetUserFeedbacksParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof userFeedbacks>>,
        TError,
        TData,
        Awaited<ReturnType<typeof userFeedbacks>>,
        QueryKey,
        GetUserFeedbacksParams["page"]
      >
    >;
  },
): UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getUserFeedbacksInfiniteQueryOptions(params, options);

  const query = useInfiniteQuery(queryOptions) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getUserFeedbacksQueryOptions = <
  TData = Awaited<ReturnType<typeof userFeedbacks>>,
  TError = ErrorType<void>,
>(
  params?: GetUserFeedbacksParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userFeedbacks>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUserFeedbacksQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof userFeedbacks>>> = ({
    signal,
  }) => userFeedbacks(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof userFeedbacks>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type UserFeedbacksQueryResult = NonNullable<
  Awaited<ReturnType<typeof userFeedbacks>>
>;
export type UserFeedbacksQueryError = ErrorType<void>;

export function useUserFeedbacks<
  TData = Awaited<ReturnType<typeof userFeedbacks>>,
  TError = ErrorType<void>,
>(
  params: undefined | GetUserFeedbacksParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userFeedbacks>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof userFeedbacks>>,
          TError,
          TData
        >,
        "initialData"
      >;
  },
): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useUserFeedbacks<
  TData = Awaited<ReturnType<typeof userFeedbacks>>,
  TError = ErrorType<void>,
>(
  params?: GetUserFeedbacksParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userFeedbacks>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof userFeedbacks>>,
          TError,
          TData
        >,
        "initialData"
      >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useUserFeedbacks<
  TData = Awaited<ReturnType<typeof userFeedbacks>>,
  TError = ErrorType<void>,
>(
  params?: GetUserFeedbacksParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userFeedbacks>>, TError, TData>
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey };
/**
 * @summary Get a list of user feedbacks
 */

export function useUserFeedbacks<
  TData = Awaited<ReturnType<typeof userFeedbacks>>,
  TError = ErrorType<void>,
>(
  params?: GetUserFeedbacksParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userFeedbacks>>, TError, TData>
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getUserFeedbacksQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Returns detailed information about a specific user feedback identified by its ID.
 * @summary Get a user feedback by ID
 */
export const userFeedback = (id: number, signal?: AbortSignal) => {
  return makeRequest<UserFeedback>({
    url: `/user_feedbacks/${encodeURIComponent(String(id))}.json`,
    method: "GET",
    signal,
  });
};

export const getUserFeedbackQueryKey = (id: number) => {
  return [`/user_feedbacks/${id}.json`] as const;
};

export const getUserFeedbackQueryOptions = <
  TData = Awaited<ReturnType<typeof userFeedback>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userFeedback>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUserFeedbackQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof userFeedback>>> = ({
    signal,
  }) => userFeedback(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof userFeedback>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type UserFeedbackQueryResult = NonNullable<
  Awaited<ReturnType<typeof userFeedback>>
>;
export type UserFeedbackQueryError = ErrorType<void>;

export function useUserFeedback<
  TData = Awaited<ReturnType<typeof userFeedback>>,
  TError = ErrorType<void>,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userFeedback>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof userFeedback>>,
          TError,
          TData
        >,
        "initialData"
      >;
  },
): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useUserFeedback<
  TData = Awaited<ReturnType<typeof userFeedback>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userFeedback>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof userFeedback>>,
          TError,
          TData
        >,
        "initialData"
      >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useUserFeedback<
  TData = Awaited<ReturnType<typeof userFeedback>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userFeedback>>, TError, TData>
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey };
/**
 * @summary Get a user feedback by ID
 */

export function useUserFeedback<
  TData = Awaited<ReturnType<typeof userFeedback>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userFeedback>>, TError, TData>
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getUserFeedbackQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
