/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */
import { makeRequest } from '../http/axios';
import type { Appeal, GetAppealsParams, UpdateAppealBody } from './model';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Returns appeals visible to the current user. Non-staff users only see their own
appeals. Several search filters are restricted to staff.

 * @summary Get a list of appeals
 */
export const appeals = (
  params?: GetAppealsParams,
  options?: SecondParameter<typeof makeRequest<Appeal[]>>,
) => {
  return makeRequest<Appeal[]>(
    { url: `/appeals.json`, method: 'GET', params },
    options,
  );
};
/**
 * Returns detailed information about a specific appeal.
 * @summary Get an appeal by ID
 */
export const appeal = (
  id: number,
  options?: SecondParameter<typeof makeRequest<Appeal>>,
) => {
  return makeRequest<Appeal>(
    { url: `/appeals/${id}.json`, method: 'GET' },
    options,
  );
};
/**
 * Updates an appeal's status and response. Claims the appeal for the current user.
If already claimed by someone else, the request redirects to a confirmation
page unless `force_claim=true` is set.

 * @summary Update an appeal
 */
export const updateAppeal = (
  id: number,
  updateAppealBody: UpdateAppealBody,
  options?: SecondParameter<typeof makeRequest<void>>,
) => {
  return makeRequest<void>(
    {
      url: `/appeals/${id}.json`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: updateAppealBody,
    },
    options,
  );
};
/**
 * Claims a pending appeal to indicate you are handling it.
 * @summary Claim an appeal
 */
export const claimAppeal = (
  id: number,
  options?: SecondParameter<typeof makeRequest<Appeal>>,
) => {
  return makeRequest<Appeal>(
    { url: `/appeals/${id}/claim.json`, method: 'POST' },
    options,
  );
};
/**
 * Releases the current user's claim on an appeal. Approved appeals cannot be unclaimed.
 * @summary Unclaim an appeal
 */
export const unclaimAppeal = (
  id: number,
  options?: SecondParameter<typeof makeRequest<Appeal>>,
) => {
  return makeRequest<Appeal>(
    { url: `/appeals/${id}/unclaim.json`, method: 'POST' },
    options,
  );
};
export type AppealsResult = NonNullable<Awaited<ReturnType<typeof appeals>>>;
export type AppealResult = NonNullable<Awaited<ReturnType<typeof appeal>>>;
export type UpdateAppealResult = NonNullable<
  Awaited<ReturnType<typeof updateAppeal>>
>;
export type ClaimAppealResult = NonNullable<
  Awaited<ReturnType<typeof claimAppeal>>
>;
export type UnclaimAppealResult = NonNullable<
  Awaited<ReturnType<typeof unclaimAppeal>>
>;
