/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.

## Authentication

Endpoints with `x-access-level` above `anonymous` require authentication.
Credentials are the account username and an API key issued by `/api_keys.json`,
submitted as either HTTP Basic (username, API key) or the query/body parameters
`login` and `api_key`.

The `x-access-level` extension declares the minimum privilege level for an
operation: `anonymous`, `logged_in`, `member`, `janitor`, `moderator`, `admin`.

 * OpenAPI spec version: dadc1e4c50658851c0205e6ecbfa4723a976b0ab
 */
import { makeRequest } from '../http/axios';
import type { GetModActionsParams, ModAction } from './model';

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

/**
 * Returns a list of moderation actions based on search criteria.
 * @summary Get a list of moderation actions
 */
export const modActions = (
  params?: GetModActionsParams,
  options?: SecondParameter<typeof makeRequest>,
) => {
  return makeRequest<ModAction[]>(
    { url: `/mod_actions.json`, method: 'GET', params },
    options,
  );
};
/**
 * Returns detailed information about a specific moderation action identified by its ID.
 * @summary Get a moderation action by ID
 */
export const modAction = (
  id: number,
  options?: SecondParameter<typeof makeRequest>,
) => {
  return makeRequest<ModAction>(
    { url: `/mod_actions/${id}.json`, method: 'GET' },
    options,
  );
};
export type ModActionsResult = NonNullable<
  Awaited<ReturnType<typeof modActions>>
>;
export type ModActionResult = NonNullable<
  Awaited<ReturnType<typeof modAction>>
>;
