/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */
import { makeRequest } from '../http/axios';
import type { GetModActionsParams, ModAction } from './model';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Returns a list of moderation actions based on search criteria.
 * @summary Get a list of moderation actions
 */
export const modActions = (
  params?: GetModActionsParams,
  options?: SecondParameter<typeof makeRequest<ModAction[]>>,
) => {
  return makeRequest<ModAction[]>(
    { url: `/mod_actions.json`, method: 'GET', params },
    options,
  );
};
/**
 * Returns detailed information about a specific moderation action identified by its ID.
 * @summary Get a moderation action by ID
 */
export const modAction = (
  id: number,
  options?: SecondParameter<typeof makeRequest<ModAction>>,
) => {
  return makeRequest<ModAction>(
    { url: `/mod_actions/${id}.json`, method: 'GET' },
    options,
  );
};
export type ModActionsResult = NonNullable<
  Awaited<ReturnType<typeof modActions>>
>;
export type ModActionResult = NonNullable<
  Awaited<ReturnType<typeof modAction>>
>;
