/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */
import { makeRequest } from '../http/axios';
import type {
  ApprovePostReplacementParams,
  CreatePostReplacement200,
  CreatePostReplacementBody,
  CreatePostReplacementForPost200,
  GetNewPostReplacementParams,
  GetPostReplacementsForPostParams,
  GetPostReplacementsParams,
  LegacyPost,
  PostReplacement,
  TransferPostReplacementParams,
} from './model';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Returns a list of post replacements based on search criteria.
 * @summary Get a list of post replacements
 */
export const postReplacements = (
  params?: GetPostReplacementsParams,
  options?: SecondParameter<typeof makeRequest<PostReplacement[]>>,
) => {
  return makeRequest<PostReplacement[]>(
    { url: `/post_replacements.json`, method: 'GET', params },
    options,
  );
};
/**
 * Creates a new post replacement for a given post.
 * @summary Create a post replacement
 */
export const createPostReplacement = (
  createPostReplacementBody: CreatePostReplacementBody,
  options?: SecondParameter<typeof makeRequest<CreatePostReplacement200>>,
) => {
  const formData = new FormData();
  formData.append(`post_id`, createPostReplacementBody.post_id.toString());
  if (
    createPostReplacementBody['post_replacement[replacement_url]'] !== undefined
  ) {
    formData.append(
      `post_replacement[replacement_url]`,
      createPostReplacementBody['post_replacement[replacement_url]'],
    );
  }
  if (
    createPostReplacementBody['post_replacement[replacement_file]'] !==
    undefined
  ) {
    formData.append(
      `post_replacement[replacement_file]`,
      createPostReplacementBody['post_replacement[replacement_file]'],
    );
  }
  if (createPostReplacementBody['post_replacement[reason]'] !== undefined) {
    formData.append(
      `post_replacement[reason]`,
      createPostReplacementBody['post_replacement[reason]'],
    );
  }
  if (createPostReplacementBody['post_replacement[source]'] !== undefined) {
    formData.append(
      `post_replacement[source]`,
      createPostReplacementBody['post_replacement[source]'],
    );
  }
  if (createPostReplacementBody['post_replacement[as_pending]'] !== undefined) {
    formData.append(
      `post_replacement[as_pending]`,
      createPostReplacementBody['post_replacement[as_pending]'].toString(),
    );
  }

  return makeRequest<CreatePostReplacement200>(
    {
      url: `/post_replacements.json`,
      method: 'POST',
      headers: { 'Content-Type': 'multipart/form-data' },
      data: formData,
    },
    options,
  );
};
/**
 * Permanently removes a post replacement.
 * @summary Destroy a post replacement
 */
export const destroyPostReplacement = (
  id: number,
  options?: SecondParameter<typeof makeRequest<void>>,
) => {
  return makeRequest<void>(
    { url: `/post_replacements/${id}.json`, method: 'DELETE' },
    options,
  );
};
/**
 * Approves a pending post replacement.
 * @summary Approve a post replacement
 */
export const approvePostReplacement = (
  id: number,
  params?: ApprovePostReplacementParams,
  options?: SecondParameter<typeof makeRequest<PostReplacement>>,
) => {
  return makeRequest<PostReplacement>(
    { url: `/post_replacements/${id}/approve.json`, method: 'PUT', params },
    options,
  );
};
/**
 * Rejects a pending post replacement.
 * @summary Reject a post replacement
 */
export const rejectPostReplacement = (
  id: number,
  options?: SecondParameter<typeof makeRequest<PostReplacement>>,
) => {
  return makeRequest<PostReplacement>(
    { url: `/post_replacements/${id}/reject.json`, method: 'PUT' },
    options,
  );
};
/**
 * Promotes a post replacement to a new post.
 * @summary Promote a post replacement
 */
export const promotePostReplacement = (
  id: number,
  options?: SecondParameter<typeof makeRequest<LegacyPost>>,
) => {
  return makeRequest<LegacyPost>(
    { url: `/post_replacements/${id}/promote.json`, method: 'POST' },
    options,
  );
};
/**
 * Toggles the penalize flag on a post replacement.
 * @summary Toggle penalize on a post replacement
 */
export const togglePenalizePostReplacement = (
  id: number,
  options?: SecondParameter<typeof makeRequest<PostReplacement>>,
) => {
  return makeRequest<PostReplacement>(
    { url: `/post_replacements/${id}/toggle_penalize.json`, method: 'PUT' },
    options,
  );
};
/**
 * Returns an unsaved post replacement attached to the given post. Requires membership of the replacements beta.
 * @summary Get a blank post replacement
 */
export const newPostReplacement = (
  params: GetNewPostReplacementParams,
  options?: SecondParameter<typeof makeRequest<PostReplacement>>,
) => {
  return makeRequest<PostReplacement>(
    { url: `/post_replacements/new.json`, method: 'GET', params },
    options,
  );
};
/**
 * Moves a pending or rejected replacement onto a different post. Returns no body on success.
 * @summary Transfer a post replacement to another post
 */
export const transferPostReplacement = (
  id: number,
  params: TransferPostReplacementParams,
  options?: SecondParameter<typeof makeRequest<void>>,
) => {
  return makeRequest<void>(
    { url: `/post_replacements/${id}/transfer.json`, method: 'PUT', params },
    options,
  );
};
/**
 * Returns the post replacements belonging to a single post.
 * @summary Get the replacements for a post
 */
export const postReplacementsForPost = (
  postId: number,
  params?: GetPostReplacementsForPostParams,
  options?: SecondParameter<typeof makeRequest<PostReplacement[]>>,
) => {
  return makeRequest<PostReplacement[]>(
    { url: `/posts/${postId}/replacements.json`, method: 'GET', params },
    options,
  );
};
/**
 * Creates a new post replacement for the post named in the path. Requires membership of the replacements beta. The `post_id` field of the body is ignored in favour of the path segment.
 * @summary Create a replacement for a post
 */
export const createPostReplacementForPost = (
  postId: number,
  createPostReplacementBody: CreatePostReplacementBody,
  options?: SecondParameter<
    typeof makeRequest<CreatePostReplacementForPost200>
  >,
) => {
  const formData = new FormData();
  formData.append(`post_id`, createPostReplacementBody.post_id.toString());
  if (
    createPostReplacementBody['post_replacement[replacement_url]'] !== undefined
  ) {
    formData.append(
      `post_replacement[replacement_url]`,
      createPostReplacementBody['post_replacement[replacement_url]'],
    );
  }
  if (
    createPostReplacementBody['post_replacement[replacement_file]'] !==
    undefined
  ) {
    formData.append(
      `post_replacement[replacement_file]`,
      createPostReplacementBody['post_replacement[replacement_file]'],
    );
  }
  if (createPostReplacementBody['post_replacement[reason]'] !== undefined) {
    formData.append(
      `post_replacement[reason]`,
      createPostReplacementBody['post_replacement[reason]'],
    );
  }
  if (createPostReplacementBody['post_replacement[source]'] !== undefined) {
    formData.append(
      `post_replacement[source]`,
      createPostReplacementBody['post_replacement[source]'],
    );
  }
  if (createPostReplacementBody['post_replacement[as_pending]'] !== undefined) {
    formData.append(
      `post_replacement[as_pending]`,
      createPostReplacementBody['post_replacement[as_pending]'].toString(),
    );
  }

  return makeRequest<CreatePostReplacementForPost200>(
    {
      url: `/posts/${postId}/replacements.json`,
      method: 'POST',
      headers: { 'Content-Type': 'multipart/form-data' },
      data: formData,
    },
    options,
  );
};
/**
 * Returns an unsaved post replacement attached to the post named in the path. Requires membership of the replacements beta.
 * @summary Get a blank replacement for a post
 */
export const newPostReplacementForPost = (
  postId: number,
  options?: SecondParameter<typeof makeRequest<PostReplacement>>,
) => {
  return makeRequest<PostReplacement>(
    { url: `/posts/${postId}/replacements/new.json`, method: 'GET' },
    options,
  );
};
export type PostReplacementsResult = NonNullable<
  Awaited<ReturnType<typeof postReplacements>>
>;
export type CreatePostReplacementResult = NonNullable<
  Awaited<ReturnType<typeof createPostReplacement>>
>;
export type DestroyPostReplacementResult = NonNullable<
  Awaited<ReturnType<typeof destroyPostReplacement>>
>;
export type ApprovePostReplacementResult = NonNullable<
  Awaited<ReturnType<typeof approvePostReplacement>>
>;
export type RejectPostReplacementResult = NonNullable<
  Awaited<ReturnType<typeof rejectPostReplacement>>
>;
export type PromotePostReplacementResult = NonNullable<
  Awaited<ReturnType<typeof promotePostReplacement>>
>;
export type TogglePenalizePostReplacementResult = NonNullable<
  Awaited<ReturnType<typeof togglePenalizePostReplacement>>
>;
export type NewPostReplacementResult = NonNullable<
  Awaited<ReturnType<typeof newPostReplacement>>
>;
export type TransferPostReplacementResult = NonNullable<
  Awaited<ReturnType<typeof transferPostReplacement>>
>;
export type PostReplacementsForPostResult = NonNullable<
  Awaited<ReturnType<typeof postReplacementsForPost>>
>;
export type CreatePostReplacementForPostResult = NonNullable<
  Awaited<ReturnType<typeof createPostReplacementForPost>>
>;
export type NewPostReplacementForPostResult = NonNullable<
  Awaited<ReturnType<typeof newPostReplacementForPost>>
>;
