/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */
import { makeRequest } from '../http/axios';
import type { GetPostEventsParams, PostEventList } from './model';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Returns a list of post events filtered by various criteria.

When `v2=true`, the response is an unwrapped array. Otherwise the array is
wrapped under `post_events`.

 * @summary Get a list of post events
 */
export const postEvents = (
  params?: GetPostEventsParams,
  options?: SecondParameter<typeof makeRequest<PostEventList>>,
) => {
  return makeRequest<PostEventList>(
    { url: `/post_events.json`, method: 'GET', params },
    options,
  );
};
export type PostEventsResult = NonNullable<
  Awaited<ReturnType<typeof postEvents>>
>;
