/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.
 * OpenAPI spec version: 1.0.0
 */
import type { GetTagAliasesParams, TagAlias } from './model';
import { makeRequest } from '../http/axios';

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

/**
 * Returns a list of tag aliases filtered by various criteria.
 * @summary Get a list of tag aliases
 */
export const tagAliases = (
  params?: GetTagAliasesParams,
  options?: SecondParameter<typeof makeRequest>,
) => {
  return makeRequest<TagAlias[]>(
    { url: `/tag_aliases.json`, method: 'GET', params },
    options,
  );
};
/**
 * Returns detailed information about a specific tag alias identified by its ID.
 * @summary Get a tag alias by ID
 */
export const tagAlias = (
  id: number,
  options?: SecondParameter<typeof makeRequest>,
) => {
  return makeRequest<TagAlias>(
    { url: `/tag_aliases/${id}.json`, method: 'GET' },
    options,
  );
};
export type TagAliasesResult = NonNullable<
  Awaited<ReturnType<typeof tagAliases>>
>;
export type TagAliasResult = NonNullable<Awaited<ReturnType<typeof tagAlias>>>;
