/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */
import { makeRequest } from '../http/axios';
import type {
  CreateUserFeedbackBody,
  GetNewUserFeedbackParams,
  GetUserFeedbacksParams,
  UpdateUserFeedbackBody,
  UserFeedback,
} from './model';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Returns a list of user feedbacks based on search criteria.
 * @summary Get a list of user feedbacks
 */
export const userFeedbacks = (
  params?: GetUserFeedbacksParams,
  options?: SecondParameter<typeof makeRequest<UserFeedback[]>>,
) => {
  return makeRequest<UserFeedback[]>(
    { url: `/user_feedbacks.json`, method: 'GET', params },
    options,
  );
};
/**
 * Leaves feedback on a user. The subject may be given by ID or by name, and may not be the creator.
 * @summary Create a user feedback
 */
export const createUserFeedback = (
  createUserFeedbackBody: CreateUserFeedbackBody,
  options?: SecondParameter<typeof makeRequest<UserFeedback>>,
) => {
  return makeRequest<UserFeedback>(
    {
      url: `/user_feedbacks.json`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createUserFeedbackBody,
    },
    options,
  );
};
/**
 * Returns detailed information about a specific user feedback identified by its ID.
 * @summary Get a user feedback by ID
 */
export const userFeedback = (
  id: number,
  options?: SecondParameter<typeof makeRequest<UserFeedback>>,
) => {
  return makeRequest<UserFeedback>(
    { url: `/user_feedbacks/${id}.json`, method: 'GET' },
    options,
  );
};
/**
 * Updates the body and/or category of an existing user feedback.
 * @summary Update a user feedback
 */
export const updateUserFeedback = (
  id: number,
  updateUserFeedbackBody: UpdateUserFeedbackBody,
  options?: SecondParameter<typeof makeRequest<void>>,
) => {
  return makeRequest<void>(
    {
      url: `/user_feedbacks/${id}.json`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: updateUserFeedbackBody,
    },
    options,
  );
};
/**
 * Removes a user feedback from the database. Only an admin, or the moderator who created it, may destroy it.
 * @summary Permanently destroy a user feedback
 */
export const destroyUserFeedback = (
  id: number,
  options?: SecondParameter<typeof makeRequest<void>>,
) => {
  return makeRequest<void>(
    { url: `/user_feedbacks/${id}.json`, method: 'DELETE' },
    options,
  );
};
/**
 * Marks a user feedback as deleted without permanently removing it.
 * @summary Soft-delete a user feedback
 */
export const deleteUserFeedback = (
  id: number,
  options?: SecondParameter<typeof makeRequest<void>>,
) => {
  return makeRequest<void>(
    { url: `/user_feedbacks/${id}/delete.json`, method: 'PUT' },
    options,
  );
};
/**
 * Restores a previously soft-deleted user feedback.
 * @summary Undelete a user feedback
 */
export const undeleteUserFeedback = (
  id: number,
  options?: SecondParameter<typeof makeRequest<void>>,
) => {
  return makeRequest<void>(
    { url: `/user_feedbacks/${id}/undelete.json`, method: 'PUT' },
    options,
  );
};
/**
 * Returns an unsaved user feedback, prefilled from any supplied query parameters.
 * @summary Get a blank user feedback
 */
export const newUserFeedback = (
  params?: GetNewUserFeedbackParams,
  options?: SecondParameter<typeof makeRequest<UserFeedback>>,
) => {
  return makeRequest<UserFeedback>(
    { url: `/user_feedbacks/new.json`, method: 'GET', params },
    options,
  );
};
/**
 * Returns the feedback to be edited. Moderators cannot edit feedback left about themselves.
 * @summary Get a user feedback for editing
 */
export const editUserFeedback = (
  id: number,
  options?: SecondParameter<typeof makeRequest<UserFeedback>>,
) => {
  return makeRequest<UserFeedback>(
    { url: `/user_feedbacks/${id}/edit.json`, method: 'GET' },
    options,
  );
};
export type UserFeedbacksResult = NonNullable<
  Awaited<ReturnType<typeof userFeedbacks>>
>;
export type CreateUserFeedbackResult = NonNullable<
  Awaited<ReturnType<typeof createUserFeedback>>
>;
export type UserFeedbackResult = NonNullable<
  Awaited<ReturnType<typeof userFeedback>>
>;
export type UpdateUserFeedbackResult = NonNullable<
  Awaited<ReturnType<typeof updateUserFeedback>>
>;
export type DestroyUserFeedbackResult = NonNullable<
  Awaited<ReturnType<typeof destroyUserFeedback>>
>;
export type DeleteUserFeedbackResult = NonNullable<
  Awaited<ReturnType<typeof deleteUserFeedback>>
>;
export type UndeleteUserFeedbackResult = NonNullable<
  Awaited<ReturnType<typeof undeleteUserFeedback>>
>;
export type NewUserFeedbackResult = NonNullable<
  Awaited<ReturnType<typeof newUserFeedback>>
>;
export type EditUserFeedbackResult = NonNullable<
  Awaited<ReturnType<typeof editUserFeedback>>
>;
