/**
 * Generated by orval. Do not edit manually.
 * e621 API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */
import { makeRequest } from '../http/axios';
import type {
  CreateStaffNoteBody,
  CreateUserBody,
  GetUsersParams,
  UpdateUserBody,
  User,
  UserAvatarMenu,
  UserProfile,
  UserUploadTags,
} from './model';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Returns a list of users based on search criteria.
 * @summary Get a list of users
 */
export const users = (
  params?: GetUsersParams,
  options?: SecondParameter<typeof makeRequest<User[]>>,
) => {
  return makeRequest<User[]>(
    { url: `/users.json`, method: 'GET', params },
    options,
  );
};
/**
 * Registers a new user account. Only available when not logged in and signups are enabled.
 * @summary Create a new user account
 */
export const createUser = (
  createUserBody: CreateUserBody,
  options?: SecondParameter<typeof makeRequest<User>>,
) => {
  return makeRequest<User>(
    {
      url: `/users.json`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createUserBody,
    },
    options,
  );
};
/**
 * Returns detailed information about a user identified by their ID or username.
 * @summary Get user information by ID or username
 */
export const user = (
  id: string,
  options?: SecondParameter<typeof makeRequest<UserProfile>>,
) => {
  return makeRequest<UserProfile>(
    { url: `/users/${id}.json`, method: 'GET' },
    options,
  );
};
/**
 * Updates the currently authenticated user's account settings. Users can only update their own account unless they are an admin.
 * @summary Update the current user's settings
 */
export const updateUser = (
  id: number,
  updateUserBody: UpdateUserBody,
  options?: SecondParameter<typeof makeRequest<void>>,
) => {
  return makeRequest<void>(
    {
      url: `/users/${id}.json`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateUserBody,
    },
    options,
  );
};
/**
 * Returns the currently authenticated user's full profile information.
 * @summary Get the current authenticated user
 */
export const currentUser = (
  options?: SecondParameter<typeof makeRequest<UserProfile>>,
) => {
  return makeRequest<UserProfile>(
    { url: `/users/me.json`, method: 'GET' },
    options,
  );
};
/**
 * Returns detailed upload limit information for a user.
 * @summary Get a user's upload limit information
 */
export const userUploadLimit = (
  id: string,
  options?: SecondParameter<typeof makeRequest<UserProfile>>,
) => {
  return makeRequest<UserProfile>(
    { url: `/users/${id}/upload_limit.json`, method: 'GET' },
    options,
  );
};
/**
 * Returns an unsaved, blank user record used to prime a signup form. Only available while logged out and when signups are enabled.
 * @summary Get a blank user record for signup
 */
export const newUser = (
  options?: SecondParameter<typeof makeRequest<User>>,
) => {
  return makeRequest<User>({ url: `/users/new.json`, method: 'GET' }, options);
};
/**
 * Returns the authenticated user's own account record. The `id` in the path is ignored: the action always loads the current user.
 * @summary Get the current user's editable account record
 */
export const editUser = (
  id: string,
  options?: SecondParameter<typeof makeRequest<User>>,
) => {
  return makeRequest<User>(
    { url: `/users/${id}/edit.json`, method: 'GET' },
    options,
  );
};
/**
 * Returns booleans telling the avatar dropdown which of the current user's content listings are non-empty.
 * @summary Get the current user's avatar menu flags
 */
export const userAvatarMenu = (
  options?: SecondParameter<typeof makeRequest<UserAvatarMenu>>,
) => {
  return makeRequest<UserAvatarMenu>(
    { url: `/users/avatar_menu.json`, method: 'GET' },
    options,
  );
};
/**
 * Returns the current user's favorite tags and the tags they most recently added to posts, for the upload tag editor.
 * @summary Get the current user's upload tag suggestions
 */
export const userUploadTags = (
  options?: SecondParameter<typeof makeRequest<UserUploadTags>>,
) => {
  return makeRequest<UserUploadTags>(
    { url: `/users/upload_tags.json`, method: 'GET' },
    options,
  );
};
/**
 * Flips a user's upload ban.

If the user's uploads are currently enabled, disabling them requires a reason, so the
action returns the user record instead of acting; submit the reason to
`/users/{id}/disable_uploads.json`. If the user's uploads are currently disabled, they
are re-enabled and the response is a redirect.

 * @summary Toggle a user's ability to upload
 */
export const toggleUserUploads = (
  id: string,
  options?: SecondParameter<typeof makeRequest<User>>,
) => {
  return makeRequest<User>(
    { url: `/users/${id}/toggle_uploads.json`, method: 'GET' },
    options,
  );
};
/**
 * Bans a user from uploading and records the supplied reason as a staff note. The reason is mandatory.
 * @summary Disable a user's ability to upload
 */
export const disableUserUploads = (
  id: string,
  createStaffNoteBody: CreateStaffNoteBody,
  options?: SecondParameter<typeof makeRequest<unknown>>,
) => {
  return makeRequest<unknown>(
    {
      url: `/users/${id}/disable_uploads.json`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createStaffNoteBody,
    },
    options,
  );
};
/**
 * Flips a user's karma-free upload ban.

If the user's unlimited uploads are currently enabled, disabling them requires a reason,
so the action returns the user record instead of acting; submit the reason to
`/users/{id}/disable_karma_free.json`. If they are currently disabled, they are
re-enabled and the response is a redirect. A user below the karma threshold is redirected
without any change.

 * @summary Toggle a user's unlimited uploads
 */
export const toggleUserKarmaFree = (
  id: string,
  options?: SecondParameter<typeof makeRequest<User>>,
) => {
  return makeRequest<User>(
    { url: `/users/${id}/toggle_karma_free.json`, method: 'GET' },
    options,
  );
};
/**
 * Revokes a user's karma-free upload bypass and records the supplied reason as a staff note. The reason is mandatory.
 * @summary Disable a user's unlimited uploads
 */
export const disableUserKarmaFree = (
  id: string,
  createStaffNoteBody: CreateStaffNoteBody,
  options?: SecondParameter<typeof makeRequest<unknown>>,
) => {
  return makeRequest<unknown>(
    {
      url: `/users/${id}/disable_karma_free.json`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createStaffNoteBody,
    },
    options,
  );
};
/**
 * Enqueues a background job that removes every favorite belonging to the user.
 * @summary Flush a user's favorites
 */
export const flushUserFavorites = (
  id: string,
  options?: SecondParameter<typeof makeRequest<unknown>>,
) => {
  return makeRequest<unknown>(
    { url: `/users/${id}/flush_favorites.json`, method: 'POST' },
    options,
  );
};
/**
 * Recomputes the user's cached post, comment, note and other counters.
 * @summary Recount a user's cached statistics
 */
export const fixUserCounts = (
  id: string,
  options?: SecondParameter<typeof makeRequest<unknown>>,
) => {
  return makeRequest<unknown>(
    { url: `/users/${id}/fix_counts.json`, method: 'GET' },
    options,
  );
};
export type UsersResult = NonNullable<Awaited<ReturnType<typeof users>>>;
export type CreateUserResult = NonNullable<
  Awaited<ReturnType<typeof createUser>>
>;
export type UserResult = NonNullable<Awaited<ReturnType<typeof user>>>;
export type UpdateUserResult = NonNullable<
  Awaited<ReturnType<typeof updateUser>>
>;
export type CurrentUserResult = NonNullable<
  Awaited<ReturnType<typeof currentUser>>
>;
export type UserUploadLimitResult = NonNullable<
  Awaited<ReturnType<typeof userUploadLimit>>
>;
export type NewUserResult = NonNullable<Awaited<ReturnType<typeof newUser>>>;
export type EditUserResult = NonNullable<Awaited<ReturnType<typeof editUser>>>;
export type UserAvatarMenuResult = NonNullable<
  Awaited<ReturnType<typeof userAvatarMenu>>
>;
export type UserUploadTagsResult = NonNullable<
  Awaited<ReturnType<typeof userUploadTags>>
>;
export type ToggleUserUploadsResult = NonNullable<
  Awaited<ReturnType<typeof toggleUserUploads>>
>;
export type DisableUserUploadsResult = NonNullable<
  Awaited<ReturnType<typeof disableUserUploads>>
>;
export type ToggleUserKarmaFreeResult = NonNullable<
  Awaited<ReturnType<typeof toggleUserKarmaFree>>
>;
export type DisableUserKarmaFreeResult = NonNullable<
  Awaited<ReturnType<typeof disableUserKarmaFree>>
>;
export type FlushUserFavoritesResult = NonNullable<
  Awaited<ReturnType<typeof flushUserFavorites>>
>;
export type FixUserCountsResult = NonNullable<
  Awaited<ReturnType<typeof fixUserCounts>>
>;
