/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * 5-thirty
 * backend data aggregate for 6 o'clock
 * OpenAPI spec version: 1.0.0
 */
import type { TimeScale } from './timeScale';
import type { Activity } from './activity';

export interface DailyActivity {
  /** The counter value */
  value: number;
  timescale: TimeScale;
  activity: Activity;
}
