/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * 5-thirty
 * backend data aggregate for 6 o'clock
 * OpenAPI spec version: 1.0.0
 */
import type { DashboardPositions } from './dashboardPositions';
import type { DashboardUpdateMeta } from './dashboardUpdateMeta';

export interface DashboardUpdate {
  version?: number;
  positions?: DashboardPositions;
  meta?: DashboardUpdateMeta;
}
