/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * 5-thirty
 * backend data aggregate for 6 o'clock
 * OpenAPI spec version: 0.0.5
 */
import type { GetActivitySeriesScale } from './getActivitySeriesScale';
import type { GetActivitySeriesArea } from './getActivitySeriesArea';

export type GetActivitySeriesParams = {
  startDate?: Date;
  endDate?: Date;
  timezone?: string;
  scale?: GetActivitySeriesScale;
  userId?: number;
  area?: GetActivitySeriesArea;
};
