/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.
 * OpenAPI spec version: 1.0.0
 */
import type { GetTicketsJsonSearchQtype } from "./getTicketsJsonSearchQtype";
import type { GetTicketsJsonSearchStatus } from "./getTicketsJsonSearchStatus";

export type GetTicketsJsonParams = {
  /**
   * The page number to retrieve
   */
  page?: number;
  /**
   * The number of tickets to retrieve per page
   */
  limit?: number;
  /**
   * Filter by the creator's username
   */
  "search[creator_name]"?: string;
  /**
   * Filter by the accused user's username
   */
  "search[accused_name]"?: string;
  /**
   * Filter by the claimant's username
   */
  "search[claimant_name]"?: string;
  /**
   * Filter by the reason for the ticket
   */
  "search[reason]"?: string;
  /**
   * Filter by the type of the ticket (e.g., user, comment, post)
   */
  "search[qtype]"?: GetTicketsJsonSearchQtype;
  /**
   * Filter by the status of the ticket
   */
  "search[status]"?: GetTicketsJsonSearchStatus;
};
