/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * e621 API
 * An API for accessing user information and other resources on e621 and e926.
 * OpenAPI spec version: 1.0.0
 */

export type GetUsersSearchOrder =
  (typeof GetUsersSearchOrder)[keyof typeof GetUsersSearchOrder];

 
export const GetUsersSearchOrder = {
  date: "date",
  name: "name",
  post_upload_count: "post_upload_count",
  note_count: "note_count",
  post_update_count: "post_update_count",
} as const;
