/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * 5-thirty
 * backend data aggregate for 6 o'clock
 * OpenAPI spec version: 0.0.2
 */

export type ManifestHealthCondition =
  (typeof ManifestHealthCondition)[keyof typeof ManifestHealthCondition];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ManifestHealthCondition = {
  nominal: 'nominal',
  degraded: 'degraded',
  abnormal: 'abnormal',
} as const;
