/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * 5-thirty
 * backend data aggregate for 6 o'clock
 * OpenAPI spec version: 0.0.4
 */
import type { ManifestType } from './manifestType';

export interface Manifest {
  endDate: Date;
  id: number;
  lowerId: number;
  startDate: Date;
  type: ManifestType;
  upperId: number;
}
