/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * 5-thirty
 * backend data aggregate for 6 o'clock
 * OpenAPI spec version: 0.0.3
 */

export type ManifestHealthType =
  (typeof ManifestHealthType)[keyof typeof ManifestHealthType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ManifestHealthType = {
  approvals: 'approvals',
  tickets: 'tickets',
  posts: 'posts',
  users: 'users',
  user_profiles: 'user_profiles',
  flags: 'flags',
  feedbacks: 'feedbacks',
} as const;
