/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * 5-thirty
 * backend data aggregate for 6 o'clock
 * OpenAPI spec version: 1.0.0
 */

export interface ManifestAvailability {
  approvals?: number;
  tickets?: number;
  posts?: number;
  users?: number;
  userProfiles?: number;
  flags?: number;
  feedbacks?: number;
  postVersions?: number;
  postReplacements?: number;
  modActions?: number;
  bulkUpdateRequests?: number;
  tagAliases?: number;
  tagImplications?: number;
}
