/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * 5-thirty
 * backend data aggregate for 6 o'clock
 * OpenAPI spec version: 0.0.8
 */

/**
 * The time scale of the counter
 */
export type TimeScale = typeof TimeScale[keyof typeof TimeScale];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TimeScale = {
  minute: 'minute',
  hour: 'hour',
  day: 'day',
  week: 'week',
  month: 'month',
  year: 'year',
  decade: 'decade',
  all: 'all',
} as const;
