/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * 5-thirty
 * backend data aggregate for 6 o'clock
 * OpenAPI spec version: 0.0.5
 */

export type TimeScale = (typeof TimeScale)[keyof typeof TimeScale];

 
export const TimeScale = {
  minute: 'minute',
  hour: 'hour',
  day: 'day',
  week: 'week',
  month: 'month',
  year: 'year',
  decade: 'decade',
  all: 'all',
} as const;
